# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/system.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_HDMI_CTL_0/system_HDMI_CTL_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_HDMI_CTL_0 || ORIG_REF_NAME==system_HDMI_CTL_0} -quiet] -quiet

# IP: bd/system/ip/system_HDMI_TX_SRC_0/system_HDMI_TX_SRC_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_HDMI_TX_SRC_0 || ORIG_REF_NAME==system_HDMI_TX_SRC_0} -quiet] -quiet

# IP: bd/system/ip/system_PMOD_IN_0/system_PMOD_IN_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_PMOD_IN_0 || ORIG_REF_NAME==system_PMOD_IN_0} -quiet] -quiet

# IP: bd/system/ip/system_PMOD_OUT_0/system_PMOD_OUT_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_PMOD_OUT_0 || ORIG_REF_NAME==system_PMOD_OUT_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_bram_ctrl_0_0/system_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_bram_ctrl_0_0 || ORIG_REF_NAME==system_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_bram_ctrl_0_bram_0/system_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==system_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/system/ip/system_CLK_125_0/system_CLK_125_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_CLK_125_0 || ORIG_REF_NAME==system_CLK_125_0} -quiet] -quiet

# IP: bd/system/ip/system_CLK_74_25_0/system_CLK_74_25_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_CLK_74_25_0 || ORIG_REF_NAME==system_CLK_74_25_0} -quiet] -quiet

# IP: bd/system/ip/system_FMC_HPC0_CLK0_M2C_0/system_FMC_HPC0_CLK0_M2C_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_FMC_HPC0_CLK0_M2C_0 || ORIG_REF_NAME==system_FMC_HPC0_CLK0_M2C_0} -quiet] -quiet

# IP: bd/system/ip/system_FMC_HPC0_CLK1_M2C_0/system_FMC_HPC0_CLK1_M2C_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_FMC_HPC0_CLK1_M2C_0 || ORIG_REF_NAME==system_FMC_HPC0_CLK1_M2C_0} -quiet] -quiet

# IP: bd/system/ip/system_FMC_HPC0_GBTCLK0_M2C_0/system_FMC_HPC0_GBTCLK0_M2C_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_FMC_HPC0_GBTCLK0_M2C_0 || ORIG_REF_NAME==system_FMC_HPC0_GBTCLK0_M2C_0} -quiet] -quiet

# IP: bd/system/ip/system_FMC_HPC0_GBTCLK1_M2C_0/system_FMC_HPC0_GBTCLK1_M2C_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_FMC_HPC0_GBTCLK1_M2C_0 || ORIG_REF_NAME==system_FMC_HPC0_GBTCLK1_M2C_0} -quiet] -quiet

# IP: bd/system/ip/system_FMC_HPC1_CLK0_M2C_0/system_FMC_HPC1_CLK0_M2C_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_FMC_HPC1_CLK0_M2C_0 || ORIG_REF_NAME==system_FMC_HPC1_CLK0_M2C_0} -quiet] -quiet

# IP: bd/system/ip/system_FMC_HPC1_GBTCLK0_M2C_0/system_FMC_HPC1_GBTCLK0_M2C_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_FMC_HPC1_GBTCLK0_M2C_0 || ORIG_REF_NAME==system_FMC_HPC1_GBTCLK0_M2C_0} -quiet] -quiet

# IP: bd/system/ip/system_HDMI_RX_CLK_0/system_HDMI_RX_CLK_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_HDMI_RX_CLK_0 || ORIG_REF_NAME==system_HDMI_RX_CLK_0} -quiet] -quiet

# IP: bd/system/ip/system_HDMI_SI5324_OUT_0/system_HDMI_SI5324_OUT_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_HDMI_SI5324_OUT_0 || ORIG_REF_NAME==system_HDMI_SI5324_OUT_0} -quiet] -quiet

# IP: bd/system/ip/system_SFP_SI5328_OUT_0/system_SFP_SI5328_OUT_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_SFP_SI5328_OUT_0 || ORIG_REF_NAME==system_SFP_SI5328_OUT_0} -quiet] -quiet

# IP: bd/system/ip/system_USER_MGT_SI570_CLOCK1_0/system_USER_MGT_SI570_CLOCK1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_USER_MGT_SI570_CLOCK1_0 || ORIG_REF_NAME==system_USER_MGT_SI570_CLOCK1_0} -quiet] -quiet

# IP: bd/system/ip/system_USER_MGT_SI570_CLOCK2_0/system_USER_MGT_SI570_CLOCK2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_USER_MGT_SI570_CLOCK2_0 || ORIG_REF_NAME==system_USER_MGT_SI570_CLOCK2_0} -quiet] -quiet

# IP: bd/system/ip/system_USER_SMA_MGT_CLOCK_0/system_USER_SMA_MGT_CLOCK_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_USER_SMA_MGT_CLOCK_0 || ORIG_REF_NAME==system_USER_SMA_MGT_CLOCK_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_0/system_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_0 || ORIG_REF_NAME==system_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/system/ip/system_diff_freq_counter_0_0/system_diff_freq_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_diff_freq_counter_0_0 || ORIG_REF_NAME==system_diff_freq_counter_0_0} -quiet] -quiet

# IP: bd/system/ip/system_diff_freq_counter_2_0/system_diff_freq_counter_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_diff_freq_counter_2_0 || ORIG_REF_NAME==system_diff_freq_counter_2_0} -quiet] -quiet

# IP: bd/system/ip/system_diff_freq_counter_3_0/system_diff_freq_counter_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_diff_freq_counter_3_0 || ORIG_REF_NAME==system_diff_freq_counter_3_0} -quiet] -quiet

# IP: bd/system/ip/system_diff_freq_counter_4_0/system_diff_freq_counter_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_diff_freq_counter_4_0 || ORIG_REF_NAME==system_diff_freq_counter_4_0} -quiet] -quiet

# IP: bd/system/ip/system_diff_freq_counter_5_0/system_diff_freq_counter_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_diff_freq_counter_5_0 || ORIG_REF_NAME==system_diff_freq_counter_5_0} -quiet] -quiet

# IP: bd/system/ip/system_gt_freq_counter_0_0/system_gt_freq_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_gt_freq_counter_0_0 || ORIG_REF_NAME==system_gt_freq_counter_0_0} -quiet] -quiet

# IP: bd/system/ip/system_gt_freq_counter_1_0/system_gt_freq_counter_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_gt_freq_counter_1_0 || ORIG_REF_NAME==system_gt_freq_counter_1_0} -quiet] -quiet

# IP: bd/system/ip/system_gt_freq_counter_2_0/system_gt_freq_counter_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_gt_freq_counter_2_0 || ORIG_REF_NAME==system_gt_freq_counter_2_0} -quiet] -quiet

# IP: bd/system/ip/system_gt_freq_counter_3_0/system_gt_freq_counter_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_gt_freq_counter_3_0 || ORIG_REF_NAME==system_gt_freq_counter_3_0} -quiet] -quiet

# IP: bd/system/ip/system_gt_freq_counter_5_0/system_gt_freq_counter_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_gt_freq_counter_5_0 || ORIG_REF_NAME==system_gt_freq_counter_5_0} -quiet] -quiet

# IP: bd/system/ip/system_gt_freq_counter_6_0/system_gt_freq_counter_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_gt_freq_counter_6_0 || ORIG_REF_NAME==system_gt_freq_counter_6_0} -quiet] -quiet

# IP: bd/system/ip/system_gt_freq_counter_7_0/system_gt_freq_counter_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_gt_freq_counter_7_0 || ORIG_REF_NAME==system_gt_freq_counter_7_0} -quiet] -quiet

# IP: bd/system/ip/system_gt_freq_counter_8_0/system_gt_freq_counter_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_gt_freq_counter_8_0 || ORIG_REF_NAME==system_gt_freq_counter_8_0} -quiet] -quiet

# IP: bd/system/ip/system_gt_freq_counter_9_0/system_gt_freq_counter_9_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_gt_freq_counter_9_0 || ORIG_REF_NAME==system_gt_freq_counter_9_0} -quiet] -quiet

# IP: bd/system/ip/system_ddr4_0_0/system_ddr4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ddr4_0_0 || ORIG_REF_NAME==system_ddr4_0_0} -quiet] -quiet

# IP: bd/system/ip/system_dip_switches_8bits_0/system_dip_switches_8bits_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dip_switches_8bits_0 || ORIG_REF_NAME==system_dip_switches_8bits_0} -quiet] -quiet

# IP: bd/system/ip/system_iic0_pl_0/system_iic0_pl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_iic0_pl_0 || ORIG_REF_NAME==system_iic0_pl_0} -quiet] -quiet

# IP: bd/system/ip/system_iic1_pl_0/system_iic1_pl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_iic1_pl_0 || ORIG_REF_NAME==system_iic1_pl_0} -quiet] -quiet

# IP: bd/system/ip/system_led_8bits_0/system_led_8bits_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_led_8bits_0 || ORIG_REF_NAME==system_led_8bits_0} -quiet] -quiet

# IP: bd/system/ip/system_microblaze_0_xlconcat_0/system_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_microblaze_0_xlconcat_0 || ORIG_REF_NAME==system_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/system/ip/system_push_buttons_5bits_0/system_push_buttons_5bits_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_push_buttons_5bits_0 || ORIG_REF_NAME==system_push_buttons_5bits_0} -quiet] -quiet

# IP: bd/system/ip/system_system_management_wiz_0_0/system_system_management_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_system_management_wiz_0_0 || ORIG_REF_NAME==system_system_management_wiz_0_0} -quiet] -quiet

# IP: bd/system/ip/system_uart2_pl_0/system_uart2_pl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_uart2_pl_0 || ORIG_REF_NAME==system_uart2_pl_0} -quiet] -quiet

# IP: bd/system/ip/system_zynq_ultra_ps_e_0_0/system_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==system_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_smc_0/system_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_smc_0 || ORIG_REF_NAME==system_axi_smc_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps8_0_99M_0/system_rst_ps8_0_99M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_ps8_0_99M_0 || ORIG_REF_NAME==system_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_ddr4_0_266M_0/system_rst_ddr4_0_266M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_ddr4_0_266M_0 || ORIG_REF_NAME==system_rst_ddr4_0_266M_0} -quiet] -quiet

# IP: bd/system/ip/system_ps8_0_axi_periph_0/system_ps8_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ps8_0_axi_periph_0 || ORIG_REF_NAME==system_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/system/ip/system_clk_wiz_1_0/system_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_clk_wiz_1_0 || ORIG_REF_NAME==system_clk_wiz_1_0} -quiet] -quiet

# IP: bd/system/ip/system_util_ds_buf_0_0/system_util_ds_buf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_ds_buf_0_0 || ORIG_REF_NAME==system_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_1/system_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_1 || ORIG_REF_NAME==system_xbar_1} -quiet] -quiet

# IP: bd/system/ip/system_auto_ds_11/system_auto_ds_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_ds_11 || ORIG_REF_NAME==system_auto_ds_11} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_11/system_auto_pc_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_11 || ORIG_REF_NAME==system_auto_pc_11} -quiet] -quiet

# IP: bd/system/ip/system_auto_ds_10/system_auto_ds_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_ds_10 || ORIG_REF_NAME==system_auto_ds_10} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_10/system_auto_pc_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_10 || ORIG_REF_NAME==system_auto_pc_10} -quiet] -quiet

# IP: bd/system/ip/system_auto_ds_9/system_auto_ds_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_ds_9 || ORIG_REF_NAME==system_auto_ds_9} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_9/system_auto_pc_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_9 || ORIG_REF_NAME==system_auto_pc_9} -quiet] -quiet

# IP: bd/system/ip/system_auto_ds_8/system_auto_ds_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_ds_8 || ORIG_REF_NAME==system_auto_ds_8} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_8/system_auto_pc_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_8 || ORIG_REF_NAME==system_auto_pc_8} -quiet] -quiet

# IP: bd/system/ip/system_auto_ds_7/system_auto_ds_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_ds_7 || ORIG_REF_NAME==system_auto_ds_7} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_7/system_auto_pc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_7 || ORIG_REF_NAME==system_auto_pc_7} -quiet] -quiet

# IP: bd/system/ip/system_auto_ds_6/system_auto_ds_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_ds_6 || ORIG_REF_NAME==system_auto_ds_6} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_6/system_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_6 || ORIG_REF_NAME==system_auto_pc_6} -quiet] -quiet

# IP: bd/system/ip/system_auto_ds_5/system_auto_ds_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_ds_5 || ORIG_REF_NAME==system_auto_ds_5} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_5/system_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_5 || ORIG_REF_NAME==system_auto_pc_5} -quiet] -quiet

# IP: bd/system/ip/system_auto_ds_4/system_auto_ds_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_ds_4 || ORIG_REF_NAME==system_auto_ds_4} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_4/system_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_4 || ORIG_REF_NAME==system_auto_pc_4} -quiet] -quiet

# IP: bd/system/ip/system_auto_ds_3/system_auto_ds_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_ds_3 || ORIG_REF_NAME==system_auto_ds_3} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_3/system_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_3 || ORIG_REF_NAME==system_auto_pc_3} -quiet] -quiet

# IP: bd/system/ip/system_auto_ds_2/system_auto_ds_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_ds_2 || ORIG_REF_NAME==system_auto_ds_2} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_2/system_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_2 || ORIG_REF_NAME==system_auto_pc_2} -quiet] -quiet

# IP: bd/system/ip/system_auto_ds_1/system_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_ds_1 || ORIG_REF_NAME==system_auto_ds_1} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_1/system_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_1 || ORIG_REF_NAME==system_auto_pc_1} -quiet] -quiet

# IP: bd/system/ip/system_auto_ds_0/system_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_ds_0 || ORIG_REF_NAME==system_auto_ds_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# XDC: bd/system/system_ooc.xdc
