# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/system_ddr4_0_0.xci
# IP: The module: 'system_ddr4_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/ip_0/system_ddr4_0_0_microblaze_mcs.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ddr4_0_0_microblaze_mcs || ORIG_REF_NAME==system_ddr4_0_0_microblaze_mcs}]

# Block Designs: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/bd_031c.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_031c || ORIG_REF_NAME==bd_031c}]

# IP: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_0/bd_031c_microblaze_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_031c_microblaze_I_0 || ORIG_REF_NAME==bd_031c_microblaze_I_0}]

# IP: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_1/bd_031c_rst_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_031c_rst_0_0 || ORIG_REF_NAME==bd_031c_rst_0_0}]

# IP: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_2/bd_031c_ilmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_031c_ilmb_0 || ORIG_REF_NAME==bd_031c_ilmb_0}]

# IP: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_3/bd_031c_dlmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_031c_dlmb_0 || ORIG_REF_NAME==bd_031c_dlmb_0}]

# IP: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_4/bd_031c_dlmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_031c_dlmb_cntlr_0 || ORIG_REF_NAME==bd_031c_dlmb_cntlr_0}]

# IP: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_5/bd_031c_ilmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_031c_ilmb_cntlr_0 || ORIG_REF_NAME==bd_031c_ilmb_cntlr_0}]

# IP: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_6/bd_031c_lmb_bram_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_031c_lmb_bram_I_0 || ORIG_REF_NAME==bd_031c_lmb_bram_I_0}]

# IP: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_7/bd_031c_second_dlmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_031c_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_031c_second_dlmb_cntlr_0}]

# IP: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_8/bd_031c_second_ilmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_031c_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_031c_second_ilmb_cntlr_0}]

# IP: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_9/bd_031c_second_lmb_bram_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_031c_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_031c_second_lmb_bram_I_0}]

# IP: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_10/bd_031c_iomodule_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_031c_iomodule_0_0 || ORIG_REF_NAME==bd_031c_iomodule_0_0}]

# IP: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/ip_1/system_ddr4_0_0_phy.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ddr4_0_0_phy || ORIG_REF_NAME==system_ddr4_0_0_phy}]

# XDC: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_0/bd_031c_microblaze_I_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_031c_microblaze_I_0 || ORIG_REF_NAME==bd_031c_microblaze_I_0}] {/U0 }]/U0 ]]

# XDC: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_0/bd_031c_microblaze_I_0_ooc_debug.xdc

# XDC: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_1/bd_031c_rst_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_031c_rst_0_0 || ORIG_REF_NAME==bd_031c_rst_0_0}] {/U0 }]/U0 ]]

# XDC: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_1/bd_031c_rst_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_031c_rst_0_0 || ORIG_REF_NAME==bd_031c_rst_0_0}] {/U0 }]/U0 ]]

# XDC: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_2/bd_031c_ilmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_031c_ilmb_0 || ORIG_REF_NAME==bd_031c_ilmb_0}] {/U0 }]/U0 ]]

# XDC: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_3/bd_031c_dlmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_031c_dlmb_0 || ORIG_REF_NAME==bd_031c_dlmb_0}] {/U0 }]/U0 ]]

# XDC: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_6/bd_031c_lmb_bram_I_0_ooc.xdc

# XDC: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_9/bd_031c_second_lmb_bram_I_0_ooc.xdc

# XDC: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_10/bd_031c_iomodule_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_031c_iomodule_0_0 || ORIG_REF_NAME==bd_031c_iomodule_0_0}] {/U0 }]/U0 ]]

# XDC: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/bd_031c_ooc.xdc

# XDC: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/ip_0/system_ddr4_0_0_microblaze_mcs_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_ddr4_0_0_microblaze_mcs || ORIG_REF_NAME==system_ddr4_0_0_microblaze_mcs}] {/inst }]/inst ]]

# XDC: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/ip_0/system_ddr4_0_0_microblaze_mcs_ooc.xdc

# XDC: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/ip_1/par/system_ddr4_0_0_phy_ooc.xdc

# XDC: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/system_ddr4_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_ddr4_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/par/system_ddr4_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_ddr4_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: C:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/system_ddr4_0_0.xci
# IP: The module: 'system_ddr4_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/ip_0/system_ddr4_0_0_microblaze_mcs.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ddr4_0_0_microblaze_mcs || ORIG_REF_NAME==system_ddr4_0_0_microblaze_mcs}]

# Block Designs: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/bd_031c.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_031c || ORIG_REF_NAME==bd_031c}]

# IP: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_0/bd_031c_microblaze_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_031c_microblaze_I_0 || ORIG_REF_NAME==bd_031c_microblaze_I_0}]

# IP: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_1/bd_031c_rst_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_031c_rst_0_0 || ORIG_REF_NAME==bd_031c_rst_0_0}]

# IP: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_2/bd_031c_ilmb_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_031c_ilmb_0 || ORIG_REF_NAME==bd_031c_ilmb_0}]

# IP: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_3/bd_031c_dlmb_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_031c_dlmb_0 || ORIG_REF_NAME==bd_031c_dlmb_0}]

# IP: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_4/bd_031c_dlmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_031c_dlmb_cntlr_0 || ORIG_REF_NAME==bd_031c_dlmb_cntlr_0}]

# IP: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_5/bd_031c_ilmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_031c_ilmb_cntlr_0 || ORIG_REF_NAME==bd_031c_ilmb_cntlr_0}]

# IP: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_6/bd_031c_lmb_bram_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_031c_lmb_bram_I_0 || ORIG_REF_NAME==bd_031c_lmb_bram_I_0}]

# IP: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_7/bd_031c_second_dlmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_031c_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_031c_second_dlmb_cntlr_0}]

# IP: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_8/bd_031c_second_ilmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_031c_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_031c_second_ilmb_cntlr_0}]

# IP: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_9/bd_031c_second_lmb_bram_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_031c_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_031c_second_lmb_bram_I_0}]

# IP: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_10/bd_031c_iomodule_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_031c_iomodule_0_0 || ORIG_REF_NAME==bd_031c_iomodule_0_0}]

# IP: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/ip_1/system_ddr4_0_0_phy.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ddr4_0_0_phy || ORIG_REF_NAME==system_ddr4_0_0_phy}]

# XDC: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_0/bd_031c_microblaze_I_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_031c_microblaze_I_0 || ORIG_REF_NAME==bd_031c_microblaze_I_0}] {/U0 }]/U0 ]]

# XDC: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_0/bd_031c_microblaze_I_0_ooc_debug.xdc

# XDC: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_1/bd_031c_rst_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_031c_rst_0_0 || ORIG_REF_NAME==bd_031c_rst_0_0}] {/U0 }]/U0 ]]

# XDC: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_1/bd_031c_rst_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_031c_rst_0_0 || ORIG_REF_NAME==bd_031c_rst_0_0}] {/U0 }]/U0 ]]

# XDC: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_2/bd_031c_ilmb_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_031c_ilmb_0 || ORIG_REF_NAME==bd_031c_ilmb_0}] {/U0 }]/U0 ]]

# XDC: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_3/bd_031c_dlmb_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_031c_dlmb_0 || ORIG_REF_NAME==bd_031c_dlmb_0}] {/U0 }]/U0 ]]

# XDC: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_6/bd_031c_lmb_bram_I_0_ooc.xdc

# XDC: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_9/bd_031c_second_lmb_bram_I_0_ooc.xdc

# XDC: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/ip/ip_10/bd_031c_iomodule_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_031c_iomodule_0_0 || ORIG_REF_NAME==bd_031c_iomodule_0_0}] {/U0 }]/U0 ]]

# XDC: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/bd_0/bd_031c_ooc.xdc

# XDC: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/ip_0/system_ddr4_0_0_microblaze_mcs_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_ddr4_0_0_microblaze_mcs || ORIG_REF_NAME==system_ddr4_0_0_microblaze_mcs}] {/inst }]/inst ]]

# XDC: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/ip_0/system_ddr4_0_0_microblaze_mcs_ooc.xdc

# XDC: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/ip_1/par/system_ddr4_0_0_phy_ooc.xdc

# XDC: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/system_ddr4_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_ddr4_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/zcu106_ipi/zcu106_ipi.srcs/sources_1/bd/system/ip/system_ddr4_0_0/par/system_ddr4_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_ddr4_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
