// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

`timescale 1 ns / 1 ps
module hls_xfft2real_top (
m_axis_dout_TVALID,
m_axis_dout_TREADY,
m_axis_dout_TDATA,
s_axis_din_TVALID,
s_axis_din_TREADY,
s_axis_din_TDATA,
s_axis_din_TLAST,
aresetn,
aclk,
ap_start,
ap_ready,
ap_done,
ap_idle
);

parameter RESET_ACTIVE_LOW = 1;

output m_axis_dout_TVALID ;
input m_axis_dout_TREADY ;
output [32 - 1:0] m_axis_dout_TDATA ;


input s_axis_din_TVALID ;
output s_axis_din_TREADY ;
input [32 - 1:0] s_axis_din_TDATA ;
input [1 - 1:0] s_axis_din_TLAST ;

input aresetn ;

input aclk ;

input ap_start ;
output ap_ready ;
output ap_done ;
output ap_idle ;


wire m_axis_dout_TVALID;
wire m_axis_dout_TREADY;
wire [32 - 1:0] m_axis_dout_TDATA;


wire s_axis_din_TVALID;
wire s_axis_din_TREADY;
wire [32 - 1:0] s_axis_din_TDATA;
wire [1 - 1:0] s_axis_din_TLAST;

wire aresetn;


wire [32 - 1:0] sig_hls_xfft2real_dout_V_din;
wire sig_hls_xfft2real_dout_V_full_n;
wire sig_hls_xfft2real_dout_V_write;

wire [33 - 1:0] sig_hls_xfft2real_din_V_dout;
wire sig_hls_xfft2real_din_V_empty_n;
wire sig_hls_xfft2real_din_V_read;

wire sig_hls_xfft2real_ap_rst;



hls_xfft2real hls_xfft2real_U(
    .dout_V_din(sig_hls_xfft2real_dout_V_din),
    .dout_V_full_n(sig_hls_xfft2real_dout_V_full_n),
    .dout_V_write(sig_hls_xfft2real_dout_V_write),
    .din_V_dout(sig_hls_xfft2real_din_V_dout),
    .din_V_empty_n(sig_hls_xfft2real_din_V_empty_n),
    .din_V_read(sig_hls_xfft2real_din_V_read),
    .ap_rst(sig_hls_xfft2real_ap_rst),
    .ap_clk(aclk),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

hls_xfft2real_m_axis_dout_if hls_xfft2real_m_axis_dout_if_U(
    .ACLK(aclk),
    .ARESETN(aresetn),
    .dout_V_din(sig_hls_xfft2real_dout_V_din),
    .dout_V_full_n(sig_hls_xfft2real_dout_V_full_n),
    .dout_V_write(sig_hls_xfft2real_dout_V_write),
    .TVALID(m_axis_dout_TVALID),
    .TREADY(m_axis_dout_TREADY),
    .TDATA(m_axis_dout_TDATA));

hls_xfft2real_s_axis_din_if hls_xfft2real_s_axis_din_if_U(
    .ACLK(aclk),
    .ARESETN(aresetn),
    .din_V_dout(sig_hls_xfft2real_din_V_dout),
    .din_V_empty_n(sig_hls_xfft2real_din_V_empty_n),
    .din_V_read(sig_hls_xfft2real_din_V_read),
    .TVALID(s_axis_din_TVALID),
    .TREADY(s_axis_din_TREADY),
    .TDATA(s_axis_din_TDATA),
    .TLAST(s_axis_din_TLAST));

hls_xfft2real_ap_rst_if #(
    .RESET_ACTIVE_LOW(RESET_ACTIVE_LOW))
ap_rst_if_U(
    .dout(sig_hls_xfft2real_ap_rst),
    .din(aresetn));

endmodule
