// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="hls_xfft2real,hls_ip_2017_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=3.890000,HLS_SYN_LAT=1036,HLS_SYN_TPT=525,HLS_SYN_MEM=6,HLS_SYN_DSP=4,HLS_SYN_FF=1632,HLS_SYN_LUT=1217}" *)

module hls_xfft2real (
        ap_clk,
        ap_rst,
        din_V_dout,
        din_V_empty_n,
        din_V_read,
        dout_V_din,
        dout_V_full_n,
        dout_V_write,
        ap_done,
        ap_start,
        ap_ready,
        ap_idle
);


input   ap_clk;
input   ap_rst;
input  [32:0] din_V_dout;
input   din_V_empty_n;
output   din_V_read;
output  [31:0] dout_V_din;
input   dout_V_full_n;
output   dout_V_write;
output   ap_done;
input   ap_start;
output   ap_ready;
output   ap_idle;

wire   [15:0] descramble_buf_0_M_i_q0;
wire   [15:0] descramble_buf_0_M_i_q1;
wire   [15:0] descramble_buf_0_M_t_q0;
wire   [15:0] descramble_buf_0_M_t_q1;
wire   [15:0] descramble_buf_1_M_i_q0;
wire   [15:0] descramble_buf_1_M_i_q1;
wire   [15:0] descramble_buf_1_M_t_q0;
wire   [15:0] descramble_buf_1_M_t_q1;
wire   [15:0] descramble_buf_0_M_1_i_q0;
wire   [15:0] descramble_buf_0_M_1_i_q1;
wire   [15:0] descramble_buf_0_M_1_t_q0;
wire   [15:0] descramble_buf_0_M_1_t_q1;
wire   [15:0] descramble_buf_1_M_1_i_q0;
wire   [15:0] descramble_buf_1_M_1_i_q1;
wire   [15:0] descramble_buf_1_M_1_t_q0;
wire   [15:0] descramble_buf_1_M_1_t_q1;
wire    Loop_realfft_be_buff_U0_ap_start;
wire    Loop_realfft_be_buff_U0_ap_done;
wire    Loop_realfft_be_buff_U0_ap_continue;
wire    Loop_realfft_be_buff_U0_ap_idle;
wire    Loop_realfft_be_buff_U0_ap_ready;
wire   [7:0] Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_address0;
wire    Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_ce0;
wire    Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_we0;
wire   [15:0] Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_d0;
wire   [7:0] Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_address0;
wire    Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_ce0;
wire    Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_we0;
wire   [15:0] Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_d0;
wire    Loop_realfft_be_buff_U0_din_V_read;
wire   [7:0] Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_address0;
wire    Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_ce0;
wire    Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_we0;
wire   [15:0] Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_d0;
wire   [7:0] Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_address0;
wire    Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_ce0;
wire    Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_we0;
wire   [15:0] Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_d0;
wire    ap_channel_done_descramble_buf_1_M;
wire    Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_full_n;
reg    ap_sync_reg_channel_write_descramble_buf_1_M;
wire    ap_sync_channel_write_descramble_buf_1_M;
wire    ap_channel_done_descramble_buf_0_M;
wire    Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_full_n;
reg    ap_sync_reg_channel_write_descramble_buf_0_M;
wire    ap_sync_channel_write_descramble_buf_0_M;
wire    ap_channel_done_descramble_buf_1_M_1;
wire    Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_full_n;
reg    ap_sync_reg_channel_write_descramble_buf_1_M_1;
wire    ap_sync_channel_write_descramble_buf_1_M_1;
wire    ap_channel_done_descramble_buf_0_M_1;
wire    Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_full_n;
reg    ap_sync_reg_channel_write_descramble_buf_0_M_1;
wire    ap_sync_channel_write_descramble_buf_0_M_1;
wire    Loop_realfft_be_desc_U0_ap_start;
wire    Loop_realfft_be_desc_U0_ap_done;
wire    Loop_realfft_be_desc_U0_ap_continue;
wire    Loop_realfft_be_desc_U0_ap_idle;
wire    Loop_realfft_be_desc_U0_ap_ready;
wire   [31:0] Loop_realfft_be_desc_U0_dout_V_din;
wire    Loop_realfft_be_desc_U0_dout_V_write;
wire   [7:0] Loop_realfft_be_desc_U0_descramble_buf_0_M_imag_V_address0;
wire    Loop_realfft_be_desc_U0_descramble_buf_0_M_imag_V_ce0;
wire   [7:0] Loop_realfft_be_desc_U0_descramble_buf_0_M_imag_V_address1;
wire    Loop_realfft_be_desc_U0_descramble_buf_0_M_imag_V_ce1;
wire   [7:0] Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_address0;
wire    Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_ce0;
wire   [7:0] Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_address1;
wire    Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_ce1;
wire   [7:0] Loop_realfft_be_desc_U0_descramble_buf_0_M_real_V_address0;
wire    Loop_realfft_be_desc_U0_descramble_buf_0_M_real_V_ce0;
wire   [7:0] Loop_realfft_be_desc_U0_descramble_buf_0_M_real_V_address1;
wire    Loop_realfft_be_desc_U0_descramble_buf_0_M_real_V_ce1;
wire   [7:0] Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_address0;
wire    Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_ce0;
wire   [7:0] Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_address1;
wire    Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_ce1;
wire    ap_sync_continue;
wire    descramble_buf_0_M_1_i_full_n;
wire    descramble_buf_0_M_1_t_empty_n;
wire   [15:0] descramble_buf_0_M_1_t_d1;
wire    descramble_buf_0_M_1_t_we1;
wire    descramble_buf_1_M_1_i_full_n;
wire    descramble_buf_1_M_1_t_empty_n;
wire   [15:0] descramble_buf_1_M_1_t_d1;
wire    descramble_buf_1_M_1_t_we1;
wire    descramble_buf_0_M_i_full_n;
wire    descramble_buf_0_M_t_empty_n;
wire   [15:0] descramble_buf_0_M_t_d1;
wire    descramble_buf_0_M_t_we1;
wire    descramble_buf_1_M_i_full_n;
wire    descramble_buf_1_M_t_empty_n;
wire   [15:0] descramble_buf_1_M_t_d1;
wire    descramble_buf_1_M_t_we1;
wire    ap_sync_done;
wire    ap_sync_ready;
wire    Loop_realfft_be_buff_U0_start_full_n;
wire    Loop_realfft_be_buff_U0_start_write;
wire    Loop_realfft_be_desc_U0_start_full_n;
wire    Loop_realfft_be_desc_U0_start_write;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_descramble_buf_1_M = 1'b0;
#0 ap_sync_reg_channel_write_descramble_buf_0_M = 1'b0;
#0 ap_sync_reg_channel_write_descramble_buf_1_M_1 = 1'b0;
#0 ap_sync_reg_channel_write_descramble_buf_0_M_1 = 1'b0;
end

hls_xfft2real_desg8j #(
    .DataWidth( 16 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
descramble_buf_0_M_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_address0),
    .i_ce0(Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_ce0),
    .i_we0(Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_we0),
    .i_d0(Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_d0),
    .i_q0(descramble_buf_0_M_i_q0),
    .i_address1(8'd0),
    .i_ce1(1'b0),
    .i_q1(descramble_buf_0_M_i_q1),
    .t_address0(Loop_realfft_be_desc_U0_descramble_buf_0_M_real_V_address0),
    .t_ce0(Loop_realfft_be_desc_U0_descramble_buf_0_M_real_V_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(descramble_buf_0_M_t_q0),
    .t_address1(Loop_realfft_be_desc_U0_descramble_buf_0_M_real_V_address1),
    .t_ce1(Loop_realfft_be_desc_U0_descramble_buf_0_M_real_V_ce1),
    .t_q1(descramble_buf_0_M_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(descramble_buf_0_M_i_full_n),
    .i_write(ap_channel_done_descramble_buf_0_M),
    .t_empty_n(descramble_buf_0_M_t_empty_n),
    .t_read(Loop_realfft_be_desc_U0_ap_ready)
);

hls_xfft2real_desg8j #(
    .DataWidth( 16 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
descramble_buf_1_M_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_address0),
    .i_ce0(Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_ce0),
    .i_we0(Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_we0),
    .i_d0(Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_d0),
    .i_q0(descramble_buf_1_M_i_q0),
    .i_address1(8'd0),
    .i_ce1(1'b0),
    .i_q1(descramble_buf_1_M_i_q1),
    .t_address0(Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_address0),
    .t_ce0(Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(descramble_buf_1_M_t_q0),
    .t_address1(Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_address1),
    .t_ce1(Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_ce1),
    .t_q1(descramble_buf_1_M_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(descramble_buf_1_M_i_full_n),
    .i_write(ap_channel_done_descramble_buf_1_M),
    .t_empty_n(descramble_buf_1_M_t_empty_n),
    .t_read(Loop_realfft_be_desc_U0_ap_ready)
);

hls_xfft2real_desg8j #(
    .DataWidth( 16 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
descramble_buf_0_M_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_address0),
    .i_ce0(Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_ce0),
    .i_we0(Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_we0),
    .i_d0(Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_d0),
    .i_q0(descramble_buf_0_M_1_i_q0),
    .i_address1(8'd0),
    .i_ce1(1'b0),
    .i_q1(descramble_buf_0_M_1_i_q1),
    .t_address0(Loop_realfft_be_desc_U0_descramble_buf_0_M_imag_V_address0),
    .t_ce0(Loop_realfft_be_desc_U0_descramble_buf_0_M_imag_V_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(descramble_buf_0_M_1_t_q0),
    .t_address1(Loop_realfft_be_desc_U0_descramble_buf_0_M_imag_V_address1),
    .t_ce1(Loop_realfft_be_desc_U0_descramble_buf_0_M_imag_V_ce1),
    .t_q1(descramble_buf_0_M_1_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(descramble_buf_0_M_1_i_full_n),
    .i_write(ap_channel_done_descramble_buf_0_M_1),
    .t_empty_n(descramble_buf_0_M_1_t_empty_n),
    .t_read(Loop_realfft_be_desc_U0_ap_ready)
);

hls_xfft2real_desg8j #(
    .DataWidth( 16 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
descramble_buf_1_M_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_address0),
    .i_ce0(Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_ce0),
    .i_we0(Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_we0),
    .i_d0(Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_d0),
    .i_q0(descramble_buf_1_M_1_i_q0),
    .i_address1(8'd0),
    .i_ce1(1'b0),
    .i_q1(descramble_buf_1_M_1_i_q1),
    .t_address0(Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_address0),
    .t_ce0(Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(descramble_buf_1_M_1_t_q0),
    .t_address1(Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_address1),
    .t_ce1(Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_ce1),
    .t_q1(descramble_buf_1_M_1_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(descramble_buf_1_M_1_i_full_n),
    .i_write(ap_channel_done_descramble_buf_1_M_1),
    .t_empty_n(descramble_buf_1_M_1_t_empty_n),
    .t_read(Loop_realfft_be_desc_U0_ap_ready)
);

Loop_realfft_be_buff Loop_realfft_be_buff_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Loop_realfft_be_buff_U0_ap_start),
    .ap_done(Loop_realfft_be_buff_U0_ap_done),
    .ap_continue(Loop_realfft_be_buff_U0_ap_continue),
    .ap_idle(Loop_realfft_be_buff_U0_ap_idle),
    .ap_ready(Loop_realfft_be_buff_U0_ap_ready),
    .descramble_buf_0_M_imag_V_address0(Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_address0),
    .descramble_buf_0_M_imag_V_ce0(Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_ce0),
    .descramble_buf_0_M_imag_V_we0(Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_we0),
    .descramble_buf_0_M_imag_V_d0(Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_d0),
    .descramble_buf_1_M_imag_V_address0(Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_address0),
    .descramble_buf_1_M_imag_V_ce0(Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_ce0),
    .descramble_buf_1_M_imag_V_we0(Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_we0),
    .descramble_buf_1_M_imag_V_d0(Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_d0),
    .din_V_dout(din_V_dout),
    .din_V_empty_n(din_V_empty_n),
    .din_V_read(Loop_realfft_be_buff_U0_din_V_read),
    .descramble_buf_0_M_real_V_address0(Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_address0),
    .descramble_buf_0_M_real_V_ce0(Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_ce0),
    .descramble_buf_0_M_real_V_we0(Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_we0),
    .descramble_buf_0_M_real_V_d0(Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_d0),
    .descramble_buf_1_M_real_V_address0(Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_address0),
    .descramble_buf_1_M_real_V_ce0(Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_ce0),
    .descramble_buf_1_M_real_V_we0(Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_we0),
    .descramble_buf_1_M_real_V_d0(Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_d0)
);

Loop_realfft_be_desc Loop_realfft_be_desc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Loop_realfft_be_desc_U0_ap_start),
    .ap_done(Loop_realfft_be_desc_U0_ap_done),
    .ap_continue(Loop_realfft_be_desc_U0_ap_continue),
    .ap_idle(Loop_realfft_be_desc_U0_ap_idle),
    .ap_ready(Loop_realfft_be_desc_U0_ap_ready),
    .dout_V_din(Loop_realfft_be_desc_U0_dout_V_din),
    .dout_V_full_n(dout_V_full_n),
    .dout_V_write(Loop_realfft_be_desc_U0_dout_V_write),
    .descramble_buf_0_M_imag_V_address0(Loop_realfft_be_desc_U0_descramble_buf_0_M_imag_V_address0),
    .descramble_buf_0_M_imag_V_ce0(Loop_realfft_be_desc_U0_descramble_buf_0_M_imag_V_ce0),
    .descramble_buf_0_M_imag_V_q0(descramble_buf_0_M_1_t_q0),
    .descramble_buf_0_M_imag_V_address1(Loop_realfft_be_desc_U0_descramble_buf_0_M_imag_V_address1),
    .descramble_buf_0_M_imag_V_ce1(Loop_realfft_be_desc_U0_descramble_buf_0_M_imag_V_ce1),
    .descramble_buf_0_M_imag_V_q1(descramble_buf_0_M_1_t_q1),
    .descramble_buf_1_M_imag_V_address0(Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_address0),
    .descramble_buf_1_M_imag_V_ce0(Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_ce0),
    .descramble_buf_1_M_imag_V_q0(descramble_buf_1_M_1_t_q0),
    .descramble_buf_1_M_imag_V_address1(Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_address1),
    .descramble_buf_1_M_imag_V_ce1(Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_ce1),
    .descramble_buf_1_M_imag_V_q1(descramble_buf_1_M_1_t_q1),
    .descramble_buf_0_M_real_V_address0(Loop_realfft_be_desc_U0_descramble_buf_0_M_real_V_address0),
    .descramble_buf_0_M_real_V_ce0(Loop_realfft_be_desc_U0_descramble_buf_0_M_real_V_ce0),
    .descramble_buf_0_M_real_V_q0(descramble_buf_0_M_t_q0),
    .descramble_buf_0_M_real_V_address1(Loop_realfft_be_desc_U0_descramble_buf_0_M_real_V_address1),
    .descramble_buf_0_M_real_V_ce1(Loop_realfft_be_desc_U0_descramble_buf_0_M_real_V_ce1),
    .descramble_buf_0_M_real_V_q1(descramble_buf_0_M_t_q1),
    .descramble_buf_1_M_real_V_address0(Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_address0),
    .descramble_buf_1_M_real_V_ce0(Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_ce0),
    .descramble_buf_1_M_real_V_q0(descramble_buf_1_M_t_q0),
    .descramble_buf_1_M_real_V_address1(Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_address1),
    .descramble_buf_1_M_real_V_ce1(Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_ce1),
    .descramble_buf_1_M_real_V_q1(descramble_buf_1_M_t_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_descramble_buf_0_M <= 1'b0;
    end else begin
        if (((Loop_realfft_be_buff_U0_ap_done & Loop_realfft_be_buff_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_descramble_buf_0_M <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_descramble_buf_0_M <= ap_sync_channel_write_descramble_buf_0_M;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_descramble_buf_0_M_1 <= 1'b0;
    end else begin
        if (((Loop_realfft_be_buff_U0_ap_done & Loop_realfft_be_buff_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_descramble_buf_0_M_1 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_descramble_buf_0_M_1 <= ap_sync_channel_write_descramble_buf_0_M_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_descramble_buf_1_M <= 1'b0;
    end else begin
        if (((Loop_realfft_be_buff_U0_ap_done & Loop_realfft_be_buff_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_descramble_buf_1_M <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_descramble_buf_1_M <= ap_sync_channel_write_descramble_buf_1_M;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_descramble_buf_1_M_1 <= 1'b0;
    end else begin
        if (((Loop_realfft_be_buff_U0_ap_done & Loop_realfft_be_buff_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_descramble_buf_1_M_1 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_descramble_buf_1_M_1 <= ap_sync_channel_write_descramble_buf_1_M_1;
        end
    end
end

assign Loop_realfft_be_buff_U0_ap_continue = (ap_sync_channel_write_descramble_buf_1_M_1 & ap_sync_channel_write_descramble_buf_1_M & ap_sync_channel_write_descramble_buf_0_M_1 & ap_sync_channel_write_descramble_buf_0_M);

assign Loop_realfft_be_buff_U0_ap_start = ap_start;

assign Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_full_n = descramble_buf_0_M_1_i_full_n;

assign Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_full_n = descramble_buf_0_M_i_full_n;

assign Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_full_n = descramble_buf_1_M_1_i_full_n;

assign Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_full_n = descramble_buf_1_M_i_full_n;

assign Loop_realfft_be_buff_U0_start_full_n = 1'b1;

assign Loop_realfft_be_buff_U0_start_write = 1'b0;

assign Loop_realfft_be_desc_U0_ap_continue = 1'b1;

assign Loop_realfft_be_desc_U0_ap_start = (descramble_buf_1_M_t_empty_n & descramble_buf_1_M_1_t_empty_n & descramble_buf_0_M_t_empty_n & descramble_buf_0_M_1_t_empty_n);

assign Loop_realfft_be_desc_U0_start_full_n = 1'b1;

assign Loop_realfft_be_desc_U0_start_write = 1'b0;

assign ap_channel_done_descramble_buf_0_M = ((ap_sync_reg_channel_write_descramble_buf_0_M ^ 1'b1) & Loop_realfft_be_buff_U0_ap_done);

assign ap_channel_done_descramble_buf_0_M_1 = ((ap_sync_reg_channel_write_descramble_buf_0_M_1 ^ 1'b1) & Loop_realfft_be_buff_U0_ap_done);

assign ap_channel_done_descramble_buf_1_M = ((ap_sync_reg_channel_write_descramble_buf_1_M ^ 1'b1) & Loop_realfft_be_buff_U0_ap_done);

assign ap_channel_done_descramble_buf_1_M_1 = ((ap_sync_reg_channel_write_descramble_buf_1_M_1 ^ 1'b1) & Loop_realfft_be_buff_U0_ap_done);

assign ap_done = Loop_realfft_be_desc_U0_ap_done;

assign ap_idle = ((descramble_buf_1_M_t_empty_n ^ 1'b1) & (descramble_buf_0_M_t_empty_n ^ 1'b1) & (descramble_buf_1_M_1_t_empty_n ^ 1'b1) & (descramble_buf_0_M_1_t_empty_n ^ 1'b1) & Loop_realfft_be_desc_U0_ap_idle & Loop_realfft_be_buff_U0_ap_idle);

assign ap_ready = Loop_realfft_be_buff_U0_ap_ready;

assign ap_sync_channel_write_descramble_buf_0_M = ((ap_channel_done_descramble_buf_0_M & Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_full_n) | ap_sync_reg_channel_write_descramble_buf_0_M);

assign ap_sync_channel_write_descramble_buf_0_M_1 = ((ap_channel_done_descramble_buf_0_M_1 & Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_full_n) | ap_sync_reg_channel_write_descramble_buf_0_M_1);

assign ap_sync_channel_write_descramble_buf_1_M = ((ap_channel_done_descramble_buf_1_M & Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_full_n) | ap_sync_reg_channel_write_descramble_buf_1_M);

assign ap_sync_channel_write_descramble_buf_1_M_1 = ((ap_channel_done_descramble_buf_1_M_1 & Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_full_n) | ap_sync_reg_channel_write_descramble_buf_1_M_1);

assign ap_sync_continue = 1'b1;

assign ap_sync_done = Loop_realfft_be_desc_U0_ap_done;

assign ap_sync_ready = Loop_realfft_be_buff_U0_ap_ready;

assign descramble_buf_0_M_1_t_d1 = 16'd0;

assign descramble_buf_0_M_1_t_we1 = 1'b0;

assign descramble_buf_0_M_t_d1 = 16'd0;

assign descramble_buf_0_M_t_we1 = 1'b0;

assign descramble_buf_1_M_1_t_d1 = 16'd0;

assign descramble_buf_1_M_1_t_we1 = 1'b0;

assign descramble_buf_1_M_t_d1 = 16'd0;

assign descramble_buf_1_M_t_we1 = 1'b0;

assign din_V_read = Loop_realfft_be_buff_U0_din_V_read;

assign dout_V_din = Loop_realfft_be_desc_U0_dout_V_din;

assign dout_V_write = Loop_realfft_be_desc_U0_dout_V_write;

endmodule //hls_xfft2real
