// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Loop_realfft_be_descramble_proc87 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        real_spectrum_lo_V_M_real_V_din,
        real_spectrum_lo_V_M_real_V_full_n,
        real_spectrum_lo_V_M_real_V_write,
        real_spectrum_lo_V_M_imag_V_din,
        real_spectrum_lo_V_M_imag_V_full_n,
        real_spectrum_lo_V_M_imag_V_write,
        real_spectrum_hi_buf_i_0_address0,
        real_spectrum_hi_buf_i_0_ce0,
        real_spectrum_hi_buf_i_0_we0,
        real_spectrum_hi_buf_i_0_d0,
        real_spectrum_hi_buf_i_1_address0,
        real_spectrum_hi_buf_i_1_ce0,
        real_spectrum_hi_buf_i_1_we0,
        real_spectrum_hi_buf_i_1_d0,
        descramble_buf_1_M_real_V_address0,
        descramble_buf_1_M_real_V_ce0,
        descramble_buf_1_M_real_V_q0,
        descramble_buf_1_M_real_V_address1,
        descramble_buf_1_M_real_V_ce1,
        descramble_buf_1_M_real_V_q1,
        descramble_buf_1_M_imag_V_address0,
        descramble_buf_1_M_imag_V_ce0,
        descramble_buf_1_M_imag_V_q0,
        descramble_buf_1_M_imag_V_address1,
        descramble_buf_1_M_imag_V_ce1,
        descramble_buf_1_M_imag_V_q1,
        descramble_buf_0_M_real_V_address0,
        descramble_buf_0_M_real_V_ce0,
        descramble_buf_0_M_real_V_q0,
        descramble_buf_0_M_imag_V_address0,
        descramble_buf_0_M_imag_V_ce0,
        descramble_buf_0_M_imag_V_q0
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state13 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
output  [15:0] real_spectrum_lo_V_M_real_V_din;
input   real_spectrum_lo_V_M_real_V_full_n;
output   real_spectrum_lo_V_M_real_V_write;
output  [15:0] real_spectrum_lo_V_M_imag_V_din;
input   real_spectrum_lo_V_M_imag_V_full_n;
output   real_spectrum_lo_V_M_imag_V_write;
output  [7:0] real_spectrum_hi_buf_i_0_address0;
output   real_spectrum_hi_buf_i_0_ce0;
output   real_spectrum_hi_buf_i_0_we0;
output  [15:0] real_spectrum_hi_buf_i_0_d0;
output  [7:0] real_spectrum_hi_buf_i_1_address0;
output   real_spectrum_hi_buf_i_1_ce0;
output   real_spectrum_hi_buf_i_1_we0;
output  [15:0] real_spectrum_hi_buf_i_1_d0;
output  [7:0] descramble_buf_1_M_real_V_address0;
output   descramble_buf_1_M_real_V_ce0;
input  [15:0] descramble_buf_1_M_real_V_q0;
output  [7:0] descramble_buf_1_M_real_V_address1;
output   descramble_buf_1_M_real_V_ce1;
input  [15:0] descramble_buf_1_M_real_V_q1;
output  [7:0] descramble_buf_1_M_imag_V_address0;
output   descramble_buf_1_M_imag_V_ce0;
input  [15:0] descramble_buf_1_M_imag_V_q0;
output  [7:0] descramble_buf_1_M_imag_V_address1;
output   descramble_buf_1_M_imag_V_ce1;
input  [15:0] descramble_buf_1_M_imag_V_q1;
output  [7:0] descramble_buf_0_M_real_V_address0;
output   descramble_buf_0_M_real_V_ce0;
input  [15:0] descramble_buf_0_M_real_V_q0;
output  [7:0] descramble_buf_0_M_imag_V_address0;
output   descramble_buf_0_M_imag_V_ce0;
input  [15:0] descramble_buf_0_M_imag_V_q0;

reg ap_done;
reg ap_idle;
reg start_write;
reg real_spectrum_hi_buf_i_0_ce0;
reg real_spectrum_hi_buf_i_0_we0;
reg real_spectrum_hi_buf_i_1_ce0;
reg real_spectrum_hi_buf_i_1_we0;
reg descramble_buf_1_M_real_V_ce0;
reg descramble_buf_1_M_real_V_ce1;
reg descramble_buf_1_M_imag_V_ce0;
reg descramble_buf_1_M_imag_V_ce1;
reg descramble_buf_0_M_real_V_ce0;
reg descramble_buf_0_M_imag_V_ce0;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
wire   [7:0] twid_rom_0_address0;
reg    twid_rom_0_ce0;
wire   [14:0] twid_rom_0_q0;
wire   [7:0] twid_rom_1_address0;
reg    twid_rom_1_ce0;
wire   [15:0] twid_rom_1_q0;
reg    real_spectrum_lo_V_M_real_V_blk_n;
reg    ap_enable_reg_pp0_iter10;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond1301_i_reg_880;
reg   [0:0] ap_reg_pp0_iter9_exitcond1301_i_reg_880;
reg    real_spectrum_lo_V_M_imag_V_blk_n;
reg   [8:0] i2_0_i_reg_236;
reg    ap_block_state1;
wire   [0:0] exitcond1301_i_fu_283_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
wire    ap_block_state6_pp0_stage0_iter4;
wire    ap_block_state7_pp0_stage0_iter5;
wire    ap_block_state8_pp0_stage0_iter6;
wire    ap_block_state9_pp0_stage0_iter7;
wire    ap_block_state10_pp0_stage0_iter8;
wire    ap_block_state11_pp0_stage0_iter9;
wire    real_spectrum_lo_V_M_real_V1_status;
reg    ap_block_state12_pp0_stage0_iter10;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] ap_reg_pp0_iter1_exitcond1301_i_reg_880;
reg   [0:0] ap_reg_pp0_iter2_exitcond1301_i_reg_880;
reg   [0:0] ap_reg_pp0_iter3_exitcond1301_i_reg_880;
reg   [0:0] ap_reg_pp0_iter4_exitcond1301_i_reg_880;
reg   [0:0] ap_reg_pp0_iter5_exitcond1301_i_reg_880;
reg   [0:0] ap_reg_pp0_iter6_exitcond1301_i_reg_880;
reg   [0:0] ap_reg_pp0_iter7_exitcond1301_i_reg_880;
reg   [0:0] ap_reg_pp0_iter8_exitcond1301_i_reg_880;
wire   [8:0] i_fu_289_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] tmp_2_fu_303_p2;
reg   [0:0] tmp_2_reg_899;
reg   [0:0] ap_reg_pp0_iter1_tmp_2_reg_899;
reg   [0:0] ap_reg_pp0_iter2_tmp_2_reg_899;
reg   [0:0] ap_reg_pp0_iter3_tmp_2_reg_899;
reg   [0:0] ap_reg_pp0_iter4_tmp_2_reg_899;
reg   [0:0] ap_reg_pp0_iter5_tmp_2_reg_899;
reg   [0:0] ap_reg_pp0_iter6_tmp_2_reg_899;
reg   [0:0] ap_reg_pp0_iter7_tmp_2_reg_899;
wire   [7:0] tmp_32_fu_325_p1;
reg   [7:0] tmp_32_reg_923;
reg   [7:0] ap_reg_pp0_iter1_tmp_32_reg_923;
reg   [7:0] ap_reg_pp0_iter2_tmp_32_reg_923;
reg   [7:0] ap_reg_pp0_iter3_tmp_32_reg_923;
reg   [7:0] ap_reg_pp0_iter4_tmp_32_reg_923;
reg   [7:0] ap_reg_pp0_iter5_tmp_32_reg_923;
reg   [7:0] ap_reg_pp0_iter6_tmp_32_reg_923;
reg   [7:0] ap_reg_pp0_iter7_tmp_32_reg_923;
reg   [7:0] ap_reg_pp0_iter8_tmp_32_reg_923;
reg   [7:0] ap_reg_pp0_iter9_tmp_32_reg_923;
reg   [15:0] p_Val2_s_reg_928;
reg   [15:0] ap_reg_pp0_iter2_p_Val2_s_reg_928;
reg   [15:0] ap_reg_pp0_iter3_p_Val2_s_reg_928;
reg   [15:0] ap_reg_pp0_iter4_p_Val2_s_reg_928;
reg   [15:0] ap_reg_pp0_iter5_p_Val2_s_reg_928;
reg   [15:0] ap_reg_pp0_iter6_p_Val2_s_reg_928;
reg   [15:0] ap_reg_pp0_iter7_p_Val2_s_reg_928;
reg   [15:0] p_Val2_1_reg_935;
reg   [15:0] ap_reg_pp0_iter2_p_Val2_1_reg_935;
reg   [15:0] ap_reg_pp0_iter3_p_Val2_1_reg_935;
reg   [15:0] ap_reg_pp0_iter4_p_Val2_1_reg_935;
reg   [15:0] ap_reg_pp0_iter5_p_Val2_1_reg_935;
reg   [15:0] ap_reg_pp0_iter6_p_Val2_1_reg_935;
reg   [15:0] ap_reg_pp0_iter7_p_Val2_1_reg_935;
reg   [15:0] p_Val2_3_reg_942;
reg    ap_enable_reg_pp0_iter1;
reg   [15:0] ap_reg_pp0_iter2_p_Val2_3_reg_942;
reg   [15:0] ap_reg_pp0_iter3_p_Val2_3_reg_942;
reg   [15:0] p_Val2_2_reg_947;
reg   [14:0] p_Val2_16_reg_952;
reg   [14:0] ap_reg_pp0_iter2_p_Val2_16_reg_952;
reg   [14:0] ap_reg_pp0_iter3_p_Val2_16_reg_952;
reg   [15:0] p_Val2_17_reg_957;
reg   [15:0] ap_reg_pp0_iter2_p_Val2_17_reg_957;
reg  signed [15:0] ap_reg_pp0_iter3_p_Val2_17_reg_957;
wire  signed [16:0] tmp_3_fu_334_p1;
reg  signed [16:0] tmp_3_reg_962;
wire  signed [16:0] tmp_10_fu_338_p1;
reg  signed [16:0] tmp_10_reg_967;
wire   [16:0] p_Val2_5_fu_341_p2;
reg   [16:0] p_Val2_5_reg_972;
reg   [15:0] tmp_16_reg_977;
reg   [0:0] tmp_11_reg_982;
reg   [15:0] tmp_12_reg_987;
reg   [15:0] tmp_13_reg_992;
wire   [15:0] p_y_M_real_V_read_assign_fu_427_p3;
reg   [15:0] p_y_M_real_V_read_assign_reg_997;
reg   [0:0] tmp_9_reg_1002;
reg   [15:0] tmp_4_reg_1007;
reg   [15:0] tmp_5_reg_1012;
wire   [15:0] f_M_imag_V_fu_500_p3;
reg   [15:0] f_M_imag_V_reg_1017;
reg   [15:0] ap_reg_pp0_iter5_f_M_imag_V_reg_1017;
reg   [15:0] ap_reg_pp0_iter6_f_M_imag_V_reg_1017;
reg   [15:0] ap_reg_pp0_iter7_f_M_imag_V_reg_1017;
reg   [0:0] tmp_18_reg_1023;
reg   [15:0] tmp_19_reg_1028;
reg   [15:0] tmp_20_reg_1033;
wire   [30:0] OP1_V_i_cast_i_fu_540_p1;
reg   [30:0] OP1_V_i_cast_i_reg_1038;
wire  signed [30:0] OP2_V_i_cast_i_fu_543_p1;
wire  signed [30:0] tmp_i_fu_546_p1;
reg  signed [30:0] tmp_i_reg_1050;
wire   [15:0] f_M_real_V_fu_554_p3;
reg   [15:0] f_M_real_V_reg_1056;
reg   [15:0] ap_reg_pp0_iter6_f_M_real_V_reg_1056;
reg   [15:0] ap_reg_pp0_iter7_f_M_real_V_reg_1056;
wire  signed [30:0] OP2_V_1_i_cast_i_fu_571_p1;
wire  signed [30:0] grp_fu_844_p2;
reg  signed [30:0] p_Val2_8_reg_1068;
wire  signed [30:0] grp_fu_850_p2;
reg  signed [30:0] tmp_1_i_cast_i_reg_1073;
reg   [15:0] p_Val2_11_reg_1078;
reg   [15:0] p_Val2_13_reg_1084;
wire   [15:0] cdata1_M_real_V_1_fu_593_p2;
wire   [15:0] cdata1_M_imag_V_1_fu_597_p2;
wire   [15:0] cdata2_M_real_V_1_fu_601_p2;
wire   [15:0] cdata2_M_imag_V_1_fu_605_p2;
wire   [15:0] cdata1_M_real_V_fu_609_p2;
wire   [15:0] cdata1_M_imag_V_fu_613_p2;
reg    ap_enable_reg_pp0_iter8;
reg   [0:0] tmp_22_reg_1130;
reg   [14:0] tmp_24_reg_1135;
wire   [15:0] tmp_26_fu_667_p2;
reg   [15:0] tmp_26_reg_1140;
reg   [0:0] tmp_27_reg_1145;
reg   [14:0] tmp_29_reg_1150;
wire   [15:0] tmp_31_fu_707_p2;
reg   [15:0] tmp_31_reg_1155;
reg   [0:0] tmp_34_reg_1160;
reg   [14:0] tmp_36_reg_1165;
wire   [15:0] tmp_38_fu_747_p2;
reg   [15:0] tmp_38_reg_1170;
reg   [0:0] tmp_40_reg_1175;
reg   [14:0] tmp_42_reg_1180;
wire   [15:0] tmp_44_fu_787_p2;
reg   [15:0] tmp_44_reg_1185;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter9;
wire   [15:0] ap_phi_reg_pp0_iter0_t_V_7_reg_247;
reg   [15:0] ap_phi_reg_pp0_iter1_t_V_7_reg_247;
reg   [15:0] ap_phi_reg_pp0_iter2_t_V_7_reg_247;
reg   [15:0] ap_phi_reg_pp0_iter3_t_V_7_reg_247;
reg   [15:0] ap_phi_reg_pp0_iter4_t_V_7_reg_247;
reg   [15:0] ap_phi_reg_pp0_iter5_t_V_7_reg_247;
reg   [15:0] ap_phi_reg_pp0_iter6_t_V_7_reg_247;
reg   [15:0] ap_phi_reg_pp0_iter7_t_V_7_reg_247;
reg   [15:0] ap_phi_reg_pp0_iter8_t_V_7_reg_247;
reg   [15:0] ap_phi_reg_pp0_iter9_t_V_7_reg_247;
wire   [15:0] ap_phi_reg_pp0_iter0_t_V_6_reg_256;
reg   [15:0] ap_phi_reg_pp0_iter1_t_V_6_reg_256;
reg   [15:0] ap_phi_reg_pp0_iter2_t_V_6_reg_256;
reg   [15:0] ap_phi_reg_pp0_iter3_t_V_6_reg_256;
reg   [15:0] ap_phi_reg_pp0_iter4_t_V_6_reg_256;
reg   [15:0] ap_phi_reg_pp0_iter5_t_V_6_reg_256;
reg   [15:0] ap_phi_reg_pp0_iter6_t_V_6_reg_256;
reg   [15:0] ap_phi_reg_pp0_iter7_t_V_6_reg_256;
reg   [15:0] ap_phi_reg_pp0_iter8_t_V_6_reg_256;
reg   [15:0] ap_phi_reg_pp0_iter9_t_V_6_reg_256;
wire   [15:0] ap_phi_reg_pp0_iter0_t_V_5_reg_265;
reg   [15:0] ap_phi_reg_pp0_iter1_t_V_5_reg_265;
reg   [15:0] ap_phi_reg_pp0_iter2_t_V_5_reg_265;
reg   [15:0] ap_phi_reg_pp0_iter3_t_V_5_reg_265;
reg   [15:0] ap_phi_reg_pp0_iter4_t_V_5_reg_265;
reg   [15:0] ap_phi_reg_pp0_iter5_t_V_5_reg_265;
reg   [15:0] ap_phi_reg_pp0_iter6_t_V_5_reg_265;
reg   [15:0] ap_phi_reg_pp0_iter7_t_V_5_reg_265;
reg   [15:0] ap_phi_reg_pp0_iter8_t_V_5_reg_265;
reg   [15:0] ap_phi_reg_pp0_iter9_t_V_5_reg_265;
wire   [15:0] ap_phi_reg_pp0_iter0_t_V_4_reg_274;
reg   [15:0] ap_phi_reg_pp0_iter1_t_V_4_reg_274;
reg   [15:0] ap_phi_reg_pp0_iter2_t_V_4_reg_274;
reg   [15:0] ap_phi_reg_pp0_iter3_t_V_4_reg_274;
reg   [15:0] ap_phi_reg_pp0_iter4_t_V_4_reg_274;
reg   [15:0] ap_phi_reg_pp0_iter5_t_V_4_reg_274;
reg   [15:0] ap_phi_reg_pp0_iter6_t_V_4_reg_274;
reg   [15:0] ap_phi_reg_pp0_iter7_t_V_4_reg_274;
reg   [15:0] ap_phi_reg_pp0_iter8_t_V_4_reg_274;
reg   [15:0] ap_phi_reg_pp0_iter9_t_V_4_reg_274;
wire   [63:0] tmp_s_fu_295_p1;
wire   [63:0] newIndex3_fu_319_p1;
wire   [63:0] tmp_33_fu_818_p1;
reg    real_spectrum_lo_V_M_real_V1_update;
reg    ap_block_pp0_stage0_01001;
wire   [7:0] tmp_fu_309_p1;
wire   [7:0] newIndex2_fu_313_p2;
wire   [15:0] p_Val2_4_fu_329_p2;
wire   [16:0] r_V_1_fu_357_p2;
wire   [17:0] tmp_26_tr_fu_361_p1;
wire   [17:0] p_neg2_fu_373_p2;
wire   [16:0] t_V_2_fu_399_p2;
wire   [0:0] tmp_15_fu_404_p3;
wire   [15:0] p_neg_t_fu_412_p2;
wire   [15:0] tmp_17_fu_417_p4;
wire  signed [16:0] tmp_6_fu_438_p1;
wire  signed [16:0] tmp_7_fu_435_p1;
wire   [16:0] r_V_fu_441_p2;
wire   [16:0] r_V_2_fu_451_p2;
wire   [17:0] tmp_21_tr_fu_447_p1;
wire   [17:0] p_neg1_fu_469_p2;
wire   [15:0] tmp_14_fu_495_p2;
wire   [17:0] tmp_33_tr_fu_457_p1;
wire   [17:0] p_neg_fu_514_p2;
wire   [15:0] tmp_8_fu_549_p2;
wire   [15:0] tmp_21_fu_560_p2;
wire   [15:0] p_y_M_imag_V_read_assign_fu_565_p3;
wire  signed [30:0] grp_fu_856_p3;
wire  signed [30:0] grp_fu_863_p3;
wire  signed [16:0] tmp_37_tr_fu_629_p1;
wire   [16:0] p_neg3_fu_641_p2;
wire   [15:0] tmp_23_fu_647_p4;
wire  signed [16:0] tmp_40_tr_fu_625_p1;
wire   [16:0] p_neg4_fu_681_p2;
wire   [15:0] tmp_28_fu_687_p4;
wire  signed [16:0] tmp_46_tr_fu_621_p1;
wire   [16:0] p_neg5_fu_721_p2;
wire   [15:0] tmp_35_fu_727_p4;
wire  signed [16:0] tmp_49_tr_fu_617_p1;
wire   [16:0] p_neg6_fu_761_p2;
wire   [15:0] tmp_41_fu_767_p4;
wire  signed [15:0] tmp_25_fu_793_p1;
wire  signed [15:0] tmp_30_fu_803_p1;
wire   [7:0] tmp_55_cast_fu_813_p2;
wire  signed [15:0] tmp_37_fu_824_p1;
wire  signed [15:0] tmp_43_fu_834_p1;
wire   [14:0] grp_fu_844_p0;
wire  signed [15:0] grp_fu_844_p1;
wire  signed [15:0] grp_fu_850_p0;
wire  signed [15:0] grp_fu_856_p0;
wire  signed [15:0] grp_fu_856_p1;
wire   [14:0] grp_fu_863_p0;
wire  signed [15:0] grp_fu_863_p1;
reg    grp_fu_844_ce;
reg    grp_fu_850_ce;
reg    grp_fu_856_ce;
reg    grp_fu_863_ce;
wire    ap_CS_fsm_state13;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [30:0] grp_fu_844_p00;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
end

Loop_realfft_be_dbkb #(
    .DataWidth( 15 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
twid_rom_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(twid_rom_0_address0),
    .ce0(twid_rom_0_ce0),
    .q0(twid_rom_0_q0)
);

Loop_realfft_be_dcud #(
    .DataWidth( 16 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
twid_rom_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(twid_rom_1_address0),
    .ce0(twid_rom_1_ce0),
    .q0(twid_rom_1_q0)
);

hls_xfft2real_muldEe #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 31 ))
hls_xfft2real_muldEe_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_844_p0),
    .din1(grp_fu_844_p1),
    .ce(grp_fu_844_ce),
    .dout(grp_fu_844_p2)
);

hls_xfft2real_muleOg #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 31 ))
hls_xfft2real_muleOg_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_850_p0),
    .din1(ap_reg_pp0_iter3_p_Val2_17_reg_957),
    .ce(grp_fu_850_ce),
    .dout(grp_fu_850_p2)
);

hls_xfft2real_macfYi #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
hls_xfft2real_macfYi_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_856_p0),
    .din1(grp_fu_856_p1),
    .din2(p_Val2_8_reg_1068),
    .ce(grp_fu_856_ce),
    .dout(grp_fu_856_p3)
);

hls_xfft2real_macg8j #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
hls_xfft2real_macg8j_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_863_p0),
    .din1(grp_fu_863_p1),
    .din2(tmp_1_i_cast_i_reg_1073),
    .ce(grp_fu_863_ce),
    .dout(grp_fu_863_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state13)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter10 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_reg_pp0_iter7_tmp_2_reg_899 == 1'd0) & (ap_reg_pp0_iter7_exitcond1301_i_reg_880 == 1'd0))) begin
            ap_phi_reg_pp0_iter9_t_V_4_reg_274 <= cdata1_M_real_V_1_fu_593_p2;
        end else if (((ap_reg_pp0_iter7_tmp_2_reg_899 == 1'd1) & (ap_reg_pp0_iter7_exitcond1301_i_reg_880 == 1'd0))) begin
            ap_phi_reg_pp0_iter9_t_V_4_reg_274 <= cdata1_M_real_V_fu_609_p2;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter9_t_V_4_reg_274 <= ap_phi_reg_pp0_iter8_t_V_4_reg_274;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_reg_pp0_iter7_tmp_2_reg_899 == 1'd0) & (ap_reg_pp0_iter7_exitcond1301_i_reg_880 == 1'd0))) begin
            ap_phi_reg_pp0_iter9_t_V_5_reg_265 <= cdata1_M_imag_V_1_fu_597_p2;
        end else if (((ap_reg_pp0_iter7_tmp_2_reg_899 == 1'd1) & (ap_reg_pp0_iter7_exitcond1301_i_reg_880 == 1'd0))) begin
            ap_phi_reg_pp0_iter9_t_V_5_reg_265 <= cdata1_M_imag_V_fu_613_p2;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter9_t_V_5_reg_265 <= ap_phi_reg_pp0_iter8_t_V_5_reg_265;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_reg_pp0_iter7_tmp_2_reg_899 == 1'd0) & (ap_reg_pp0_iter7_exitcond1301_i_reg_880 == 1'd0))) begin
            ap_phi_reg_pp0_iter9_t_V_6_reg_256 <= cdata2_M_real_V_1_fu_601_p2;
        end else if (((ap_reg_pp0_iter7_tmp_2_reg_899 == 1'd1) & (ap_reg_pp0_iter7_exitcond1301_i_reg_880 == 1'd0))) begin
            ap_phi_reg_pp0_iter9_t_V_6_reg_256 <= descramble_buf_1_M_real_V_q1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter9_t_V_6_reg_256 <= ap_phi_reg_pp0_iter8_t_V_6_reg_256;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_reg_pp0_iter7_tmp_2_reg_899 == 1'd0) & (ap_reg_pp0_iter7_exitcond1301_i_reg_880 == 1'd0))) begin
            ap_phi_reg_pp0_iter9_t_V_7_reg_247 <= cdata2_M_imag_V_1_fu_605_p2;
        end else if (((ap_reg_pp0_iter7_tmp_2_reg_899 == 1'd1) & (ap_reg_pp0_iter7_exitcond1301_i_reg_880 == 1'd0))) begin
            ap_phi_reg_pp0_iter9_t_V_7_reg_247 <= descramble_buf_1_M_imag_V_q1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter9_t_V_7_reg_247 <= ap_phi_reg_pp0_iter8_t_V_7_reg_247;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i2_0_i_reg_236 <= 9'd0;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (exitcond1301_i_fu_283_p2 == 1'd0))) begin
        i2_0_i_reg_236 <= i_fu_289_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_reg_pp0_iter3_tmp_2_reg_899 == 1'd0) & (ap_reg_pp0_iter3_exitcond1301_i_reg_880 == 1'd0))) begin
        OP1_V_i_cast_i_reg_1038[14 : 0] <= OP1_V_i_cast_i_fu_540_p1[14 : 0];
        f_M_imag_V_reg_1017 <= f_M_imag_V_fu_500_p3;
        tmp_18_reg_1023 <= r_V_2_fu_451_p2[32'd16];
        tmp_19_reg_1028 <= {{p_neg_fu_514_p2[16:1]}};
        tmp_20_reg_1033 <= {{r_V_2_fu_451_p2[16:1]}};
        tmp_4_reg_1007 <= {{p_neg1_fu_469_p2[16:1]}};
        tmp_5_reg_1012 <= {{r_V_fu_441_p2[16:1]}};
        tmp_9_reg_1002 <= r_V_fu_441_p2[32'd16];
        tmp_i_reg_1050 <= tmp_i_fu_546_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter1_t_V_4_reg_274 <= ap_phi_reg_pp0_iter0_t_V_4_reg_274;
        ap_phi_reg_pp0_iter1_t_V_5_reg_265 <= ap_phi_reg_pp0_iter0_t_V_5_reg_265;
        ap_phi_reg_pp0_iter1_t_V_6_reg_256 <= ap_phi_reg_pp0_iter0_t_V_6_reg_256;
        ap_phi_reg_pp0_iter1_t_V_7_reg_247 <= ap_phi_reg_pp0_iter0_t_V_7_reg_247;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter2_t_V_4_reg_274 <= ap_phi_reg_pp0_iter1_t_V_4_reg_274;
        ap_phi_reg_pp0_iter2_t_V_5_reg_265 <= ap_phi_reg_pp0_iter1_t_V_5_reg_265;
        ap_phi_reg_pp0_iter2_t_V_6_reg_256 <= ap_phi_reg_pp0_iter1_t_V_6_reg_256;
        ap_phi_reg_pp0_iter2_t_V_7_reg_247 <= ap_phi_reg_pp0_iter1_t_V_7_reg_247;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter3_t_V_4_reg_274 <= ap_phi_reg_pp0_iter2_t_V_4_reg_274;
        ap_phi_reg_pp0_iter3_t_V_5_reg_265 <= ap_phi_reg_pp0_iter2_t_V_5_reg_265;
        ap_phi_reg_pp0_iter3_t_V_6_reg_256 <= ap_phi_reg_pp0_iter2_t_V_6_reg_256;
        ap_phi_reg_pp0_iter3_t_V_7_reg_247 <= ap_phi_reg_pp0_iter2_t_V_7_reg_247;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter4_t_V_4_reg_274 <= ap_phi_reg_pp0_iter3_t_V_4_reg_274;
        ap_phi_reg_pp0_iter4_t_V_5_reg_265 <= ap_phi_reg_pp0_iter3_t_V_5_reg_265;
        ap_phi_reg_pp0_iter4_t_V_6_reg_256 <= ap_phi_reg_pp0_iter3_t_V_6_reg_256;
        ap_phi_reg_pp0_iter4_t_V_7_reg_247 <= ap_phi_reg_pp0_iter3_t_V_7_reg_247;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter5_t_V_4_reg_274 <= ap_phi_reg_pp0_iter4_t_V_4_reg_274;
        ap_phi_reg_pp0_iter5_t_V_5_reg_265 <= ap_phi_reg_pp0_iter4_t_V_5_reg_265;
        ap_phi_reg_pp0_iter5_t_V_6_reg_256 <= ap_phi_reg_pp0_iter4_t_V_6_reg_256;
        ap_phi_reg_pp0_iter5_t_V_7_reg_247 <= ap_phi_reg_pp0_iter4_t_V_7_reg_247;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter6_t_V_4_reg_274 <= ap_phi_reg_pp0_iter5_t_V_4_reg_274;
        ap_phi_reg_pp0_iter6_t_V_5_reg_265 <= ap_phi_reg_pp0_iter5_t_V_5_reg_265;
        ap_phi_reg_pp0_iter6_t_V_6_reg_256 <= ap_phi_reg_pp0_iter5_t_V_6_reg_256;
        ap_phi_reg_pp0_iter6_t_V_7_reg_247 <= ap_phi_reg_pp0_iter5_t_V_7_reg_247;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter7_t_V_4_reg_274 <= ap_phi_reg_pp0_iter6_t_V_4_reg_274;
        ap_phi_reg_pp0_iter7_t_V_5_reg_265 <= ap_phi_reg_pp0_iter6_t_V_5_reg_265;
        ap_phi_reg_pp0_iter7_t_V_6_reg_256 <= ap_phi_reg_pp0_iter6_t_V_6_reg_256;
        ap_phi_reg_pp0_iter7_t_V_7_reg_247 <= ap_phi_reg_pp0_iter6_t_V_7_reg_247;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter8_t_V_4_reg_274 <= ap_phi_reg_pp0_iter7_t_V_4_reg_274;
        ap_phi_reg_pp0_iter8_t_V_5_reg_265 <= ap_phi_reg_pp0_iter7_t_V_5_reg_265;
        ap_phi_reg_pp0_iter8_t_V_6_reg_256 <= ap_phi_reg_pp0_iter7_t_V_6_reg_256;
        ap_phi_reg_pp0_iter8_t_V_7_reg_247 <= ap_phi_reg_pp0_iter7_t_V_7_reg_247;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_reg_pp0_iter1_exitcond1301_i_reg_880 <= exitcond1301_i_reg_880;
        ap_reg_pp0_iter1_tmp_2_reg_899 <= tmp_2_reg_899;
        ap_reg_pp0_iter1_tmp_32_reg_923 <= tmp_32_reg_923;
        exitcond1301_i_reg_880 <= exitcond1301_i_fu_283_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_reg_pp0_iter2_exitcond1301_i_reg_880 <= ap_reg_pp0_iter1_exitcond1301_i_reg_880;
        ap_reg_pp0_iter2_p_Val2_16_reg_952 <= p_Val2_16_reg_952;
        ap_reg_pp0_iter2_p_Val2_17_reg_957 <= p_Val2_17_reg_957;
        ap_reg_pp0_iter2_p_Val2_1_reg_935 <= p_Val2_1_reg_935;
        ap_reg_pp0_iter2_p_Val2_3_reg_942 <= p_Val2_3_reg_942;
        ap_reg_pp0_iter2_p_Val2_s_reg_928 <= p_Val2_s_reg_928;
        ap_reg_pp0_iter2_tmp_2_reg_899 <= ap_reg_pp0_iter1_tmp_2_reg_899;
        ap_reg_pp0_iter2_tmp_32_reg_923 <= ap_reg_pp0_iter1_tmp_32_reg_923;
        ap_reg_pp0_iter3_exitcond1301_i_reg_880 <= ap_reg_pp0_iter2_exitcond1301_i_reg_880;
        ap_reg_pp0_iter3_p_Val2_16_reg_952 <= ap_reg_pp0_iter2_p_Val2_16_reg_952;
        ap_reg_pp0_iter3_p_Val2_17_reg_957 <= ap_reg_pp0_iter2_p_Val2_17_reg_957;
        ap_reg_pp0_iter3_p_Val2_1_reg_935 <= ap_reg_pp0_iter2_p_Val2_1_reg_935;
        ap_reg_pp0_iter3_p_Val2_3_reg_942 <= ap_reg_pp0_iter2_p_Val2_3_reg_942;
        ap_reg_pp0_iter3_p_Val2_s_reg_928 <= ap_reg_pp0_iter2_p_Val2_s_reg_928;
        ap_reg_pp0_iter3_tmp_2_reg_899 <= ap_reg_pp0_iter2_tmp_2_reg_899;
        ap_reg_pp0_iter3_tmp_32_reg_923 <= ap_reg_pp0_iter2_tmp_32_reg_923;
        ap_reg_pp0_iter4_exitcond1301_i_reg_880 <= ap_reg_pp0_iter3_exitcond1301_i_reg_880;
        ap_reg_pp0_iter4_p_Val2_1_reg_935 <= ap_reg_pp0_iter3_p_Val2_1_reg_935;
        ap_reg_pp0_iter4_p_Val2_s_reg_928 <= ap_reg_pp0_iter3_p_Val2_s_reg_928;
        ap_reg_pp0_iter4_tmp_2_reg_899 <= ap_reg_pp0_iter3_tmp_2_reg_899;
        ap_reg_pp0_iter4_tmp_32_reg_923 <= ap_reg_pp0_iter3_tmp_32_reg_923;
        ap_reg_pp0_iter5_exitcond1301_i_reg_880 <= ap_reg_pp0_iter4_exitcond1301_i_reg_880;
        ap_reg_pp0_iter5_f_M_imag_V_reg_1017 <= f_M_imag_V_reg_1017;
        ap_reg_pp0_iter5_p_Val2_1_reg_935 <= ap_reg_pp0_iter4_p_Val2_1_reg_935;
        ap_reg_pp0_iter5_p_Val2_s_reg_928 <= ap_reg_pp0_iter4_p_Val2_s_reg_928;
        ap_reg_pp0_iter5_tmp_2_reg_899 <= ap_reg_pp0_iter4_tmp_2_reg_899;
        ap_reg_pp0_iter5_tmp_32_reg_923 <= ap_reg_pp0_iter4_tmp_32_reg_923;
        ap_reg_pp0_iter6_exitcond1301_i_reg_880 <= ap_reg_pp0_iter5_exitcond1301_i_reg_880;
        ap_reg_pp0_iter6_f_M_imag_V_reg_1017 <= ap_reg_pp0_iter5_f_M_imag_V_reg_1017;
        ap_reg_pp0_iter6_f_M_real_V_reg_1056 <= f_M_real_V_reg_1056;
        ap_reg_pp0_iter6_p_Val2_1_reg_935 <= ap_reg_pp0_iter5_p_Val2_1_reg_935;
        ap_reg_pp0_iter6_p_Val2_s_reg_928 <= ap_reg_pp0_iter5_p_Val2_s_reg_928;
        ap_reg_pp0_iter6_tmp_2_reg_899 <= ap_reg_pp0_iter5_tmp_2_reg_899;
        ap_reg_pp0_iter6_tmp_32_reg_923 <= ap_reg_pp0_iter5_tmp_32_reg_923;
        ap_reg_pp0_iter7_exitcond1301_i_reg_880 <= ap_reg_pp0_iter6_exitcond1301_i_reg_880;
        ap_reg_pp0_iter7_f_M_imag_V_reg_1017 <= ap_reg_pp0_iter6_f_M_imag_V_reg_1017;
        ap_reg_pp0_iter7_f_M_real_V_reg_1056 <= ap_reg_pp0_iter6_f_M_real_V_reg_1056;
        ap_reg_pp0_iter7_p_Val2_1_reg_935 <= ap_reg_pp0_iter6_p_Val2_1_reg_935;
        ap_reg_pp0_iter7_p_Val2_s_reg_928 <= ap_reg_pp0_iter6_p_Val2_s_reg_928;
        ap_reg_pp0_iter7_tmp_2_reg_899 <= ap_reg_pp0_iter6_tmp_2_reg_899;
        ap_reg_pp0_iter7_tmp_32_reg_923 <= ap_reg_pp0_iter6_tmp_32_reg_923;
        ap_reg_pp0_iter8_exitcond1301_i_reg_880 <= ap_reg_pp0_iter7_exitcond1301_i_reg_880;
        ap_reg_pp0_iter8_tmp_32_reg_923 <= ap_reg_pp0_iter7_tmp_32_reg_923;
        ap_reg_pp0_iter9_exitcond1301_i_reg_880 <= ap_reg_pp0_iter8_exitcond1301_i_reg_880;
        ap_reg_pp0_iter9_tmp_32_reg_923 <= ap_reg_pp0_iter8_tmp_32_reg_923;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_reg_pp0_iter4_tmp_2_reg_899 == 1'd0) & (ap_reg_pp0_iter4_exitcond1301_i_reg_880 == 1'd0))) begin
        f_M_real_V_reg_1056 <= f_M_real_V_fu_554_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_reg_pp0_iter6_tmp_2_reg_899 == 1'd0) & (ap_reg_pp0_iter6_exitcond1301_i_reg_880 == 1'd0))) begin
        p_Val2_11_reg_1078 <= {{grp_fu_856_p3[30:15]}};
        p_Val2_13_reg_1084 <= {{grp_fu_863_p3[30:15]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_reg_899 == 1'd0) & (exitcond1301_i_reg_880 == 1'd0))) begin
        p_Val2_16_reg_952 <= twid_rom_0_q0;
        p_Val2_17_reg_957 <= twid_rom_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (exitcond1301_i_reg_880 == 1'd0))) begin
        p_Val2_1_reg_935 <= descramble_buf_0_M_imag_V_q0;
        p_Val2_s_reg_928 <= descramble_buf_0_M_real_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_reg_899 == 1'd0) & (exitcond1301_i_reg_880 == 1'd0))) begin
        p_Val2_2_reg_947 <= descramble_buf_1_M_imag_V_q0;
        p_Val2_3_reg_942 <= descramble_buf_1_M_real_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_reg_pp0_iter1_tmp_2_reg_899 == 1'd0) & (ap_reg_pp0_iter1_exitcond1301_i_reg_880 == 1'd0))) begin
        p_Val2_5_reg_972 <= p_Val2_5_fu_341_p2;
        tmp_10_reg_967 <= tmp_10_fu_338_p1;
        tmp_16_reg_977 <= {{p_Val2_5_fu_341_p2[16:1]}};
        tmp_3_reg_962 <= tmp_3_fu_334_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_reg_pp0_iter5_tmp_2_reg_899 == 1'd0) & (ap_reg_pp0_iter5_exitcond1301_i_reg_880 == 1'd0))) begin
        p_Val2_8_reg_1068 <= grp_fu_844_p2;
        tmp_1_i_cast_i_reg_1073 <= grp_fu_850_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_reg_pp0_iter2_tmp_2_reg_899 == 1'd0) & (ap_reg_pp0_iter2_exitcond1301_i_reg_880 == 1'd0))) begin
        p_y_M_real_V_read_assign_reg_997 <= p_y_M_real_V_read_assign_fu_427_p3;
        tmp_11_reg_982 <= r_V_1_fu_357_p2[32'd16];
        tmp_12_reg_987 <= {{p_neg2_fu_373_p2[16:1]}};
        tmp_13_reg_992 <= {{r_V_1_fu_357_p2[16:1]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_reg_pp0_iter8_exitcond1301_i_reg_880 == 1'd0))) begin
        tmp_22_reg_1130 <= ap_phi_reg_pp0_iter9_t_V_4_reg_274[32'd15];
        tmp_24_reg_1135 <= {{ap_phi_reg_pp0_iter9_t_V_4_reg_274[15:1]}};
        tmp_26_reg_1140 <= tmp_26_fu_667_p2;
        tmp_27_reg_1145 <= ap_phi_reg_pp0_iter9_t_V_5_reg_265[32'd15];
        tmp_29_reg_1150 <= {{ap_phi_reg_pp0_iter9_t_V_5_reg_265[15:1]}};
        tmp_31_reg_1155 <= tmp_31_fu_707_p2;
        tmp_34_reg_1160 <= ap_phi_reg_pp0_iter9_t_V_6_reg_256[32'd15];
        tmp_36_reg_1165 <= {{ap_phi_reg_pp0_iter9_t_V_6_reg_256[15:1]}};
        tmp_38_reg_1170 <= tmp_38_fu_747_p2;
        tmp_40_reg_1175 <= ap_phi_reg_pp0_iter9_t_V_7_reg_247[32'd15];
        tmp_42_reg_1180 <= {{ap_phi_reg_pp0_iter9_t_V_7_reg_247[15:1]}};
        tmp_44_reg_1185 <= tmp_44_fu_787_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (exitcond1301_i_fu_283_p2 == 1'd0))) begin
        tmp_2_reg_899 <= tmp_2_fu_303_p2;
        tmp_32_reg_923 <= tmp_32_fu_325_p1;
    end
end

always @ (*) begin
    if ((exitcond1301_i_fu_283_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        descramble_buf_0_M_imag_V_ce0 = 1'b1;
    end else begin
        descramble_buf_0_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        descramble_buf_0_M_real_V_ce0 = 1'b1;
    end else begin
        descramble_buf_0_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        descramble_buf_1_M_imag_V_ce0 = 1'b1;
    end else begin
        descramble_buf_1_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        descramble_buf_1_M_imag_V_ce1 = 1'b1;
    end else begin
        descramble_buf_1_M_imag_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        descramble_buf_1_M_real_V_ce0 = 1'b1;
    end else begin
        descramble_buf_1_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        descramble_buf_1_M_real_V_ce1 = 1'b1;
    end else begin
        descramble_buf_1_M_real_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_844_ce = 1'b1;
    end else begin
        grp_fu_844_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_850_ce = 1'b1;
    end else begin
        grp_fu_850_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_856_ce = 1'b1;
    end else begin
        grp_fu_856_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_863_ce = 1'b1;
    end else begin
        grp_fu_863_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        real_spectrum_hi_buf_i_0_ce0 = 1'b1;
    end else begin
        real_spectrum_hi_buf_i_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_reg_pp0_iter9_exitcond1301_i_reg_880 == 1'd0))) begin
        real_spectrum_hi_buf_i_0_we0 = 1'b1;
    end else begin
        real_spectrum_hi_buf_i_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        real_spectrum_hi_buf_i_1_ce0 = 1'b1;
    end else begin
        real_spectrum_hi_buf_i_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_reg_pp0_iter9_exitcond1301_i_reg_880 == 1'd0))) begin
        real_spectrum_hi_buf_i_1_we0 = 1'b1;
    end else begin
        real_spectrum_hi_buf_i_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (ap_reg_pp0_iter9_exitcond1301_i_reg_880 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        real_spectrum_lo_V_M_imag_V_blk_n = real_spectrum_lo_V_M_imag_V_full_n;
    end else begin
        real_spectrum_lo_V_M_imag_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_reg_pp0_iter9_exitcond1301_i_reg_880 == 1'd0))) begin
        real_spectrum_lo_V_M_real_V1_update = 1'b1;
    end else begin
        real_spectrum_lo_V_M_real_V1_update = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (ap_reg_pp0_iter9_exitcond1301_i_reg_880 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        real_spectrum_lo_V_M_real_V_blk_n = real_spectrum_lo_V_M_real_V_full_n;
    end else begin
        real_spectrum_lo_V_M_real_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        twid_rom_0_ce0 = 1'b1;
    end else begin
        twid_rom_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        twid_rom_1_ce0 = 1'b1;
    end else begin
        twid_rom_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (exitcond1301_i_fu_283_p2 == 1'd1)) & ~((ap_enable_reg_pp0_iter9 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter10 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (exitcond1301_i_fu_283_p2 == 1'd1)) | ((ap_enable_reg_pp0_iter9 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter10 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign OP1_V_i_cast_i_fu_540_p1 = ap_reg_pp0_iter3_p_Val2_16_reg_952;

assign OP2_V_1_i_cast_i_fu_571_p1 = $signed(p_y_M_imag_V_read_assign_fu_565_p3);

assign OP2_V_i_cast_i_fu_543_p1 = $signed(p_y_M_real_V_read_assign_reg_997);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((real_spectrum_lo_V_M_real_V1_status == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b1) & (ap_reg_pp0_iter9_exitcond1301_i_reg_880 == 1'd0));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((real_spectrum_lo_V_M_real_V1_status == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b1) & (ap_reg_pp0_iter9_exitcond1301_i_reg_880 == 1'd0));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((real_spectrum_lo_V_M_real_V1_status == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b1) & (ap_reg_pp0_iter9_exitcond1301_i_reg_880 == 1'd0));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state10_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state12_pp0_stage0_iter10 = ((real_spectrum_lo_V_M_real_V1_status == 1'b0) & (ap_reg_pp0_iter9_exitcond1301_i_reg_880 == 1'd0));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_t_V_4_reg_274 = 'bx;

assign ap_phi_reg_pp0_iter0_t_V_5_reg_265 = 'bx;

assign ap_phi_reg_pp0_iter0_t_V_6_reg_256 = 'bx;

assign ap_phi_reg_pp0_iter0_t_V_7_reg_247 = 'bx;

assign ap_ready = internal_ap_ready;

assign cdata1_M_imag_V_1_fu_597_p2 = (ap_reg_pp0_iter7_f_M_imag_V_reg_1017 + p_Val2_13_reg_1084);

assign cdata1_M_imag_V_fu_613_p2 = (ap_reg_pp0_iter7_p_Val2_s_reg_928 - ap_reg_pp0_iter7_p_Val2_1_reg_935);

assign cdata1_M_real_V_1_fu_593_p2 = (ap_reg_pp0_iter7_f_M_real_V_reg_1056 + p_Val2_11_reg_1078);

assign cdata1_M_real_V_fu_609_p2 = (ap_reg_pp0_iter7_p_Val2_1_reg_935 + ap_reg_pp0_iter7_p_Val2_s_reg_928);

assign cdata2_M_imag_V_1_fu_605_p2 = (p_Val2_13_reg_1084 - ap_reg_pp0_iter7_f_M_imag_V_reg_1017);

assign cdata2_M_real_V_1_fu_601_p2 = (ap_reg_pp0_iter7_f_M_real_V_reg_1056 - p_Val2_11_reg_1078);

assign descramble_buf_0_M_imag_V_address0 = tmp_s_fu_295_p1;

assign descramble_buf_0_M_real_V_address0 = tmp_s_fu_295_p1;

assign descramble_buf_1_M_imag_V_address0 = newIndex3_fu_319_p1;

assign descramble_buf_1_M_imag_V_address1 = 64'd0;

assign descramble_buf_1_M_real_V_address0 = newIndex3_fu_319_p1;

assign descramble_buf_1_M_real_V_address1 = 64'd0;

assign exitcond1301_i_fu_283_p2 = ((i2_0_i_reg_236 == 9'd256) ? 1'b1 : 1'b0);

assign f_M_imag_V_fu_500_p3 = ((tmp_11_reg_982[0:0] === 1'b1) ? tmp_14_fu_495_p2 : tmp_13_reg_992);

assign f_M_real_V_fu_554_p3 = ((tmp_9_reg_1002[0:0] === 1'b1) ? tmp_8_fu_549_p2 : tmp_5_reg_1012);

assign grp_fu_844_p0 = grp_fu_844_p00;

assign grp_fu_844_p00 = ap_reg_pp0_iter3_p_Val2_16_reg_952;

assign grp_fu_844_p1 = OP2_V_i_cast_i_fu_543_p1;

assign grp_fu_850_p0 = OP2_V_i_cast_i_fu_543_p1;

assign grp_fu_856_p0 = tmp_i_reg_1050;

assign grp_fu_856_p1 = OP2_V_1_i_cast_i_fu_571_p1;

assign grp_fu_863_p0 = OP1_V_i_cast_i_reg_1038;

assign grp_fu_863_p1 = OP2_V_1_i_cast_i_fu_571_p1;

assign i_fu_289_p2 = (i2_0_i_reg_236 + 9'd1);

assign newIndex2_fu_313_p2 = (8'd0 - tmp_fu_309_p1);

assign newIndex3_fu_319_p1 = newIndex2_fu_313_p2;

assign p_Val2_4_fu_329_p2 = (16'd0 - p_Val2_2_reg_947);

assign p_Val2_5_fu_341_p2 = ($signed(tmp_3_fu_334_p1) - $signed(tmp_10_fu_338_p1));

assign p_neg1_fu_469_p2 = (18'd0 - tmp_21_tr_fu_447_p1);

assign p_neg2_fu_373_p2 = (18'd0 - tmp_26_tr_fu_361_p1);

assign p_neg3_fu_641_p2 = ($signed(17'd0) - $signed(tmp_37_tr_fu_629_p1));

assign p_neg4_fu_681_p2 = ($signed(17'd0) - $signed(tmp_40_tr_fu_625_p1));

assign p_neg5_fu_721_p2 = ($signed(17'd0) - $signed(tmp_46_tr_fu_621_p1));

assign p_neg6_fu_761_p2 = ($signed(17'd0) - $signed(tmp_49_tr_fu_617_p1));

assign p_neg_fu_514_p2 = (18'd0 - tmp_33_tr_fu_457_p1);

assign p_neg_t_fu_412_p2 = (16'd0 - tmp_16_reg_977);

assign p_y_M_imag_V_read_assign_fu_565_p3 = ((tmp_18_reg_1023[0:0] === 1'b1) ? tmp_21_fu_560_p2 : tmp_20_reg_1033);

assign p_y_M_real_V_read_assign_fu_427_p3 = ((tmp_15_fu_404_p3[0:0] === 1'b1) ? p_neg_t_fu_412_p2 : tmp_17_fu_417_p4);

assign r_V_1_fu_357_p2 = ($signed(tmp_10_reg_967) + $signed(tmp_3_reg_962));

assign r_V_2_fu_451_p2 = ($signed(tmp_7_fu_435_p1) - $signed(tmp_6_fu_438_p1));

assign r_V_fu_441_p2 = ($signed(tmp_6_fu_438_p1) + $signed(tmp_7_fu_435_p1));

assign real_spectrum_hi_buf_i_0_address0 = tmp_33_fu_818_p1;

assign real_spectrum_hi_buf_i_0_d0 = ((tmp_34_reg_1160[0:0] === 1'b1) ? tmp_38_reg_1170 : tmp_37_fu_824_p1);

assign real_spectrum_hi_buf_i_1_address0 = tmp_33_fu_818_p1;

assign real_spectrum_hi_buf_i_1_d0 = ((tmp_40_reg_1175[0:0] === 1'b1) ? tmp_44_reg_1185 : tmp_43_fu_834_p1);

assign real_spectrum_lo_V_M_imag_V_din = ((tmp_27_reg_1145[0:0] === 1'b1) ? tmp_31_reg_1155 : tmp_30_fu_803_p1);

assign real_spectrum_lo_V_M_imag_V_write = real_spectrum_lo_V_M_real_V1_update;

assign real_spectrum_lo_V_M_real_V1_status = (real_spectrum_lo_V_M_real_V_full_n & real_spectrum_lo_V_M_imag_V_full_n);

assign real_spectrum_lo_V_M_real_V_din = ((tmp_22_reg_1130[0:0] === 1'b1) ? tmp_26_reg_1140 : tmp_25_fu_793_p1);

assign real_spectrum_lo_V_M_real_V_write = real_spectrum_lo_V_M_real_V1_update;

assign start_out = real_start;

assign t_V_2_fu_399_p2 = (17'd0 - p_Val2_5_reg_972);

assign tmp_10_fu_338_p1 = $signed(p_Val2_1_reg_935);

assign tmp_14_fu_495_p2 = (16'd0 - tmp_12_reg_987);

assign tmp_15_fu_404_p3 = t_V_2_fu_399_p2[32'd16];

assign tmp_17_fu_417_p4 = {{t_V_2_fu_399_p2[16:1]}};

assign tmp_21_fu_560_p2 = (16'd0 - tmp_19_reg_1028);

assign tmp_21_tr_fu_447_p1 = r_V_fu_441_p2;

assign tmp_23_fu_647_p4 = {{p_neg3_fu_641_p2[16:1]}};

assign tmp_25_fu_793_p1 = $signed(tmp_24_reg_1135);

assign tmp_26_fu_667_p2 = (16'd0 - tmp_23_fu_647_p4);

assign tmp_26_tr_fu_361_p1 = r_V_1_fu_357_p2;

assign tmp_28_fu_687_p4 = {{p_neg4_fu_681_p2[16:1]}};

assign tmp_2_fu_303_p2 = ((i2_0_i_reg_236 == 9'd0) ? 1'b1 : 1'b0);

assign tmp_30_fu_803_p1 = $signed(tmp_29_reg_1150);

assign tmp_31_fu_707_p2 = (16'd0 - tmp_28_fu_687_p4);

assign tmp_32_fu_325_p1 = i2_0_i_reg_236[7:0];

assign tmp_33_fu_818_p1 = tmp_55_cast_fu_813_p2;

assign tmp_33_tr_fu_457_p1 = r_V_2_fu_451_p2;

assign tmp_35_fu_727_p4 = {{p_neg5_fu_721_p2[16:1]}};

assign tmp_37_fu_824_p1 = $signed(tmp_36_reg_1165);

assign tmp_37_tr_fu_629_p1 = $signed(ap_phi_reg_pp0_iter9_t_V_4_reg_274);

assign tmp_38_fu_747_p2 = (16'd0 - tmp_35_fu_727_p4);

assign tmp_3_fu_334_p1 = $signed(p_Val2_4_fu_329_p2);

assign tmp_40_tr_fu_625_p1 = $signed(ap_phi_reg_pp0_iter9_t_V_5_reg_265);

assign tmp_41_fu_767_p4 = {{p_neg6_fu_761_p2[16:1]}};

assign tmp_43_fu_834_p1 = $signed(tmp_42_reg_1180);

assign tmp_44_fu_787_p2 = (16'd0 - tmp_41_fu_767_p4);

assign tmp_46_tr_fu_621_p1 = $signed(ap_phi_reg_pp0_iter9_t_V_6_reg_256);

assign tmp_49_tr_fu_617_p1 = $signed(ap_phi_reg_pp0_iter9_t_V_7_reg_247);

assign tmp_55_cast_fu_813_p2 = (8'd0 - ap_reg_pp0_iter9_tmp_32_reg_923);

assign tmp_6_fu_438_p1 = $signed(ap_reg_pp0_iter3_p_Val2_s_reg_928);

assign tmp_7_fu_435_p1 = $signed(ap_reg_pp0_iter3_p_Val2_3_reg_942);

assign tmp_8_fu_549_p2 = (16'd0 - tmp_4_reg_1007);

assign tmp_fu_309_p1 = i2_0_i_reg_236[7:0];

assign tmp_i_fu_546_p1 = ap_reg_pp0_iter3_p_Val2_17_reg_957;

assign tmp_s_fu_295_p1 = i2_0_i_reg_236;

assign twid_rom_0_address0 = tmp_s_fu_295_p1;

assign twid_rom_1_address0 = tmp_s_fu_295_p1;

always @ (posedge ap_clk) begin
    OP1_V_i_cast_i_reg_1038[30:15] <= 16'b0000000000000000;
end

endmodule //Loop_realfft_be_descramble_proc87
