# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Zynq_Design/Zynq_Design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Design || ORIG_REF_NAME==Zynq_Design} -quiet] -quiet

# IP: bd/Zynq_Design/ip/Zynq_Design_processing_system7_0_0/Zynq_Design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Design_processing_system7_0_0 || ORIG_REF_NAME==Zynq_Design_processing_system7_0_0} -quiet] -quiet

# IP: bd/Zynq_Design/ip/Zynq_Design_hls_macc_0_0/Zynq_Design_hls_macc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Design_hls_macc_0_0 || ORIG_REF_NAME==Zynq_Design_hls_macc_0_0} -quiet] -quiet

# IP: bd/Zynq_Design/ip/Zynq_Design_ps7_0_axi_periph_0/Zynq_Design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Design_ps7_0_axi_periph_0 || ORIG_REF_NAME==Zynq_Design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Zynq_Design/ip/Zynq_Design_rst_ps7_0_50M_0/Zynq_Design_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Design_rst_ps7_0_50M_0 || ORIG_REF_NAME==Zynq_Design_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/Zynq_Design/ip/Zynq_Design_auto_pc_0/Zynq_Design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Design_auto_pc_0 || ORIG_REF_NAME==Zynq_Design_auto_pc_0} -quiet] -quiet

# XDC: bd/Zynq_Design/Zynq_Design_ooc.xdc
