// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Loop_realfft_be_buffer_proc86 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        descramble_buf_0_M_imag_V_address0,
        descramble_buf_0_M_imag_V_ce0,
        descramble_buf_0_M_imag_V_we0,
        descramble_buf_0_M_imag_V_d0,
        descramble_buf_1_M_imag_V_address0,
        descramble_buf_1_M_imag_V_ce0,
        descramble_buf_1_M_imag_V_we0,
        descramble_buf_1_M_imag_V_d0,
        din_TDATA,
        din_TVALID,
        din_TREADY,
        din_TLAST,
        descramble_buf_0_M_real_V_address0,
        descramble_buf_0_M_real_V_ce0,
        descramble_buf_0_M_real_V_we0,
        descramble_buf_0_M_real_V_d0,
        descramble_buf_1_M_real_V_address0,
        descramble_buf_1_M_real_V_ce0,
        descramble_buf_1_M_real_V_we0,
        descramble_buf_1_M_real_V_d0
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [7:0] descramble_buf_0_M_imag_V_address0;
output   descramble_buf_0_M_imag_V_ce0;
output   descramble_buf_0_M_imag_V_we0;
output  [15:0] descramble_buf_0_M_imag_V_d0;
output  [7:0] descramble_buf_1_M_imag_V_address0;
output   descramble_buf_1_M_imag_V_ce0;
output   descramble_buf_1_M_imag_V_we0;
output  [15:0] descramble_buf_1_M_imag_V_d0;
input  [31:0] din_TDATA;
input   din_TVALID;
output   din_TREADY;
input  [0:0] din_TLAST;
output  [7:0] descramble_buf_0_M_real_V_address0;
output   descramble_buf_0_M_real_V_ce0;
output   descramble_buf_0_M_real_V_we0;
output  [15:0] descramble_buf_0_M_real_V_d0;
output  [7:0] descramble_buf_1_M_real_V_address0;
output   descramble_buf_1_M_real_V_ce0;
output   descramble_buf_1_M_real_V_we0;
output  [15:0] descramble_buf_1_M_real_V_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg descramble_buf_0_M_imag_V_ce0;
reg descramble_buf_0_M_imag_V_we0;
reg descramble_buf_1_M_imag_V_ce0;
reg descramble_buf_1_M_imag_V_we0;
reg descramble_buf_0_M_real_V_ce0;
reg descramble_buf_0_M_real_V_we0;
reg descramble_buf_1_M_real_V_ce0;
reg descramble_buf_1_M_real_V_we0;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] exitcond1302_i_fu_156_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    din_V_data_0_vld_out;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_enable_reg_pp0_iter1;
reg    ap_block_pp0_stage0_11001;
reg   [31:0] din_V_data_0_data_out;
wire    din_V_data_0_vld_in;
wire    din_V_data_0_ack_in;
reg    din_V_data_0_ack_out;
reg   [31:0] din_V_data_0_payload_A;
reg   [31:0] din_V_data_0_payload_B;
reg    din_V_data_0_sel_rd;
reg    din_V_data_0_sel_wr;
wire    din_V_data_0_sel;
wire    din_V_data_0_load_A;
wire    din_V_data_0_load_B;
reg   [1:0] din_V_data_0_state;
wire    din_V_data_0_state_cmp_full;
wire    din_V_last_V_0_vld_in;
reg    din_V_last_V_0_ack_out;
reg   [1:0] din_V_last_V_0_state;
reg    din_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg   [8:0] val_assign_reg_118;
reg   [7:0] newIndex_fu_132_p4;
reg   [7:0] newIndex_reg_193;
reg   [0:0] tmp_42_reg_198;
wire   [8:0] i_fu_150_p2;
reg   [8:0] i_reg_202;
reg   [0:0] exitcond1302_i_reg_207;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg   [8:0] ap_phi_mux_val_assign_phi_fu_122_p6;
wire   [63:0] newIndex1_fu_166_p1;
wire   [15:0] tmp_41_fu_173_p1;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_204;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 din_V_data_0_sel_rd = 1'b0;
#0 din_V_data_0_sel_wr = 1'b0;
#0 din_V_data_0_state = 2'd0;
#0 din_V_last_V_0_state = 2'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond1302_i_reg_207 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        din_V_data_0_sel_rd <= 1'b0;
    end else begin
        if (((din_V_data_0_ack_out == 1'b1) & (din_V_data_0_vld_out == 1'b1))) begin
            din_V_data_0_sel_rd <= ~din_V_data_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        din_V_data_0_sel_wr <= 1'b0;
    end else begin
        if (((din_V_data_0_ack_in == 1'b1) & (din_V_data_0_vld_in == 1'b1))) begin
            din_V_data_0_sel_wr <= ~din_V_data_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        din_V_data_0_state <= 2'd0;
    end else begin
        if ((((din_V_data_0_state == 2'd2) & (din_V_data_0_vld_in == 1'b0)) | ((din_V_data_0_state == 2'd3) & (din_V_data_0_vld_in == 1'b0) & (din_V_data_0_ack_out == 1'b1)))) begin
            din_V_data_0_state <= 2'd2;
        end else if ((((din_V_data_0_state == 2'd1) & (din_V_data_0_ack_out == 1'b0)) | ((din_V_data_0_state == 2'd3) & (din_V_data_0_ack_out == 1'b0) & (din_V_data_0_vld_in == 1'b1)))) begin
            din_V_data_0_state <= 2'd1;
        end else if (((~((din_V_data_0_vld_in == 1'b0) & (din_V_data_0_ack_out == 1'b1)) & ~((din_V_data_0_ack_out == 1'b0) & (din_V_data_0_vld_in == 1'b1)) & (din_V_data_0_state == 2'd3)) | ((din_V_data_0_state == 2'd1) & (din_V_data_0_ack_out == 1'b1)) | ((din_V_data_0_state == 2'd2) & (din_V_data_0_vld_in == 1'b1)))) begin
            din_V_data_0_state <= 2'd3;
        end else begin
            din_V_data_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        din_V_last_V_0_state <= 2'd0;
    end else begin
        if ((((din_V_last_V_0_state == 2'd2) & (din_V_last_V_0_vld_in == 1'b0)) | ((din_V_last_V_0_state == 2'd3) & (din_V_last_V_0_vld_in == 1'b0) & (din_V_last_V_0_ack_out == 1'b1)))) begin
            din_V_last_V_0_state <= 2'd2;
        end else if ((((din_V_last_V_0_state == 2'd1) & (din_V_last_V_0_ack_out == 1'b0)) | ((din_V_last_V_0_state == 2'd3) & (din_V_last_V_0_ack_out == 1'b0) & (din_V_last_V_0_vld_in == 1'b1)))) begin
            din_V_last_V_0_state <= 2'd1;
        end else if (((~((din_V_last_V_0_vld_in == 1'b0) & (din_V_last_V_0_ack_out == 1'b1)) & ~((din_V_last_V_0_ack_out == 1'b0) & (din_V_last_V_0_vld_in == 1'b1)) & (din_V_last_V_0_state == 2'd3)) | ((din_V_last_V_0_state == 2'd1) & (din_V_last_V_0_ack_out == 1'b1)) | ((din_V_last_V_0_state == 2'd2) & (din_V_last_V_0_vld_in == 1'b1)))) begin
            din_V_last_V_0_state <= 2'd3;
        end else begin
            din_V_last_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1302_i_reg_207 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        val_assign_reg_118 <= i_reg_202;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (exitcond1302_i_reg_207 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        val_assign_reg_118 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((din_V_data_0_load_A == 1'b1)) begin
        din_V_data_0_payload_A <= din_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((din_V_data_0_load_B == 1'b1)) begin
        din_V_data_0_payload_B <= din_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exitcond1302_i_reg_207 <= exitcond1302_i_fu_156_p2;
        newIndex_reg_193 <= newIndex_fu_132_p4;
        tmp_42_reg_198 <= ap_phi_mux_val_assign_phi_fu_122_p6[32'd0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_reg_202 <= i_fu_150_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond1302_i_reg_207 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_204)) begin
        if ((exitcond1302_i_reg_207 == 1'd1)) begin
            ap_phi_mux_val_assign_phi_fu_122_p6 = 9'd0;
        end else if ((exitcond1302_i_reg_207 == 1'd0)) begin
            ap_phi_mux_val_assign_phi_fu_122_p6 = i_reg_202;
        end else begin
            ap_phi_mux_val_assign_phi_fu_122_p6 = val_assign_reg_118;
        end
    end else begin
        ap_phi_mux_val_assign_phi_fu_122_p6 = val_assign_reg_118;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond1302_i_fu_156_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        descramble_buf_0_M_imag_V_ce0 = 1'b1;
    end else begin
        descramble_buf_0_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_42_reg_198 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        descramble_buf_0_M_imag_V_we0 = 1'b1;
    end else begin
        descramble_buf_0_M_imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        descramble_buf_0_M_real_V_ce0 = 1'b1;
    end else begin
        descramble_buf_0_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_42_reg_198 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        descramble_buf_0_M_real_V_we0 = 1'b1;
    end else begin
        descramble_buf_0_M_real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        descramble_buf_1_M_imag_V_ce0 = 1'b1;
    end else begin
        descramble_buf_1_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_42_reg_198 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        descramble_buf_1_M_imag_V_we0 = 1'b1;
    end else begin
        descramble_buf_1_M_imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        descramble_buf_1_M_real_V_ce0 = 1'b1;
    end else begin
        descramble_buf_1_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_42_reg_198 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        descramble_buf_1_M_real_V_we0 = 1'b1;
    end else begin
        descramble_buf_1_M_real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_TDATA_blk_n = din_V_data_0_state[1'd0];
    end else begin
        din_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_V_data_0_ack_out = 1'b1;
    end else begin
        din_V_data_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((din_V_data_0_sel == 1'b1)) begin
        din_V_data_0_data_out = din_V_data_0_payload_B;
    end else begin
        din_V_data_0_data_out = din_V_data_0_payload_A;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_V_last_V_0_ack_out = 1'b1;
    end else begin
        din_V_last_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((ap_reset_idle_pp0 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((din_V_data_0_vld_out == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((din_V_data_0_vld_out == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = (din_V_data_0_vld_out == 1'b0);
end

always @ (*) begin
    ap_condition_204 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign descramble_buf_0_M_imag_V_address0 = newIndex1_fu_166_p1;

assign descramble_buf_0_M_imag_V_d0 = {{din_V_data_0_data_out[31:16]}};

assign descramble_buf_0_M_real_V_address0 = newIndex1_fu_166_p1;

assign descramble_buf_0_M_real_V_d0 = tmp_41_fu_173_p1;

assign descramble_buf_1_M_imag_V_address0 = newIndex1_fu_166_p1;

assign descramble_buf_1_M_imag_V_d0 = {{din_V_data_0_data_out[31:16]}};

assign descramble_buf_1_M_real_V_address0 = newIndex1_fu_166_p1;

assign descramble_buf_1_M_real_V_d0 = tmp_41_fu_173_p1;

assign din_TREADY = din_V_last_V_0_state[1'd1];

assign din_V_data_0_ack_in = din_V_data_0_state[1'd1];

assign din_V_data_0_load_A = (~din_V_data_0_sel_wr & din_V_data_0_state_cmp_full);

assign din_V_data_0_load_B = (din_V_data_0_state_cmp_full & din_V_data_0_sel_wr);

assign din_V_data_0_sel = din_V_data_0_sel_rd;

assign din_V_data_0_state_cmp_full = ((din_V_data_0_state != 2'd1) ? 1'b1 : 1'b0);

assign din_V_data_0_vld_in = din_TVALID;

assign din_V_data_0_vld_out = din_V_data_0_state[1'd0];

assign din_V_last_V_0_vld_in = din_TVALID;

assign exitcond1302_i_fu_156_p2 = ((ap_phi_mux_val_assign_phi_fu_122_p6 == 9'd511) ? 1'b1 : 1'b0);

assign i_fu_150_p2 = (9'd1 + ap_phi_mux_val_assign_phi_fu_122_p6);

assign newIndex1_fu_166_p1 = newIndex_reg_193;

integer ap_tvar_int_0;

always @ (ap_phi_mux_val_assign_phi_fu_122_p6) begin
    for (ap_tvar_int_0 = 8 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 8 - 1) begin
            newIndex_fu_132_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            newIndex_fu_132_p4[ap_tvar_int_0] = ap_phi_mux_val_assign_phi_fu_122_p6[8 - ap_tvar_int_0];
        end
    end
end

assign tmp_41_fu_173_p1 = din_V_data_0_data_out[15:0];

endmodule //Loop_realfft_be_buffer_proc86
